import { useEffect, useState } from 'react'
import { ClipboardList, Filter } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { AuditLog, Business } from '../types'
export function AuditPage(){const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[logs,setLogs]=useState<AuditLog[]>([]);const[table,setTable]=useState('all');const[allowed,setAllowed]=useState(true)
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');if(!['owner','manager'].includes(m.role))setAllowed(false);const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b)})()},[navigate])
 useEffect(()=>{if(!business||!allowed)return;(async()=>{let q=supabase.from('audit_logs').select('*').eq('business_id',business.id).order('created_at',{ascending:false}).limit(250);if(table!=='all')q=q.eq('table_name',table);const{data}=await q;setLogs((data||[]) as AuditLog[])})()},[business,table,allowed])
 if(!business)return <div className="center-screen">Carregando auditoria...</div>;return <main className="admin-page"><AdminSidebar businessName={business.name} current="audit"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">SEGURANÇA E RASTREABILIDADE</span><h1>Auditoria</h1></div><div className="admin-head-actions"><Filter size={16}/><select className="input" value={table} onChange={e=>setTable(e.target.value)}><option value="all">Todas as áreas</option><option value="appointments">Agendamentos</option><option value="clients">Clientes</option><option value="services">Serviços</option><option value="professionals">Profissionais</option><option value="financial_transactions">Financeiro</option><option value="schedule_blocks">Bloqueios</option><option value="business_members">Equipe</option></select></div></div>{!allowed?<section className="panel-card"><h2>Acesso restrito</h2><p>Somente proprietário e gerente podem consultar o histórico de auditoria.</p></section>:<section className="panel-card"><div className="panel-title"><div><ClipboardList/><h2>Últimas alterações</h2></div><span>{logs.length} eventos</span></div><div className="audit-list">{logs.map(l=><article key={l.id}><span className={`audit-action ${l.action.toLowerCase()}`}>{l.action}</span><div><b>{label(l.table_name)}</b><small>{new Date(l.created_at).toLocaleString('pt-BR')} • {l.actor_user_id?`Usuário ${l.actor_user_id.slice(0,8)}`:'Ação pública/sistema'}</small></div><code>{l.record_id?.slice(0,8)||'—'}</code></article>)}{!logs.length&&<p className="empty-inline">Nenhum evento registrado.</p>}</div></section>}</section></main>}
function label(v:string){return({appointments:'Agendamento',clients:'Cliente',services:'Serviço',professionals:'Profissional',financial_transactions:'Financeiro',schedule_blocks:'Bloqueio',business_members:'Equipe'} as Record<string,string>)[v]||v}
