import { FormEvent, useCallback, useEffect, useState } from 'react'
import { CalendarOff, Clock3, Plus, Radio, Save, Trash2, X } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business, Professional, ScheduleBlock, WeeklyHour } from '../types'
const days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado']
const defaultHours=()=>days.map((_,day)=>({day_of_week:day,is_open:day!==0,open_time:'08:00',close_time:day===6?'14:00':'19:00'}))
export function AvailabilityPage(){
 const navigate=useNavigate();const[searchParams]=useSearchParams();const[business,setBusiness]=useState<Business|null>(null);const[role,setRole]=useState('professional');const[linkedProfessionalId,setLinkedProfessionalId]=useState<string|null>(null);const[professionals,setProfessionals]=useState<Professional[]>([]);const[businessHours,setBusinessHours]=useState<WeeklyHour[]>(defaultHours());const[professionalId,setProfessionalId]=useState('');const[proHours,setProHours]=useState<WeeklyHour[]>(defaultHours());const[blocks,setBlocks]=useState<ScheduleBlock[]>([]);const[live,setLive]=useState(false);const[message,setMessage]=useState('');const[block,setBlock]=useState({professional_id:'',start_date:'',end_date:'',start_time:'',end_time:'',reason:''})
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role,professional_id').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setRole(m.role);setLinkedProfessionalId(m.professional_id||null);if(m.role==='professional'&&m.professional_id)setProfessionalId(m.professional_id);setBlock(v=>({...v,professional_id:m.role==='professional'?(m.professional_id||''):v.professional_id}));const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b)})()},[navigate])
 const load=useCallback(async()=>{if(!business)return;const[{data:p},{data:h},{data:b}]=await Promise.all([supabase.from('professionals').select('*').eq('business_id',business.id).order('name'),supabase.from('business_hours').select('*').eq('business_id',business.id).order('day_of_week'),supabase.from('schedule_blocks').select('*,professionals(name)').eq('business_id',business.id).gte('end_date',new Date().toISOString().slice(0,10)).order('start_date').order('start_time')]);setProfessionals((p||[]) as Professional[]);if(h?.length)setBusinessHours(mergeHours(h as WeeklyHour[]));setBlocks((b||[]) as ScheduleBlock[])},[business])
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!business)return;const ch=supabase.channel(`availability-admin:${business.id}`).on('postgres_changes',{event:'*',schema:'public',table:'schedule_blocks',filter:`business_id=eq.${business.id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'business_hours',filter:`business_id=eq.${business.id}`},load).subscribe(s=>setLive(s==='SUBSCRIBED'));return()=>{supabase.removeChannel(ch)}},[business,load])
 useEffect(()=>{const requested=searchParams.get('professional');if(requested&&professionals.some(p=>p.id===requested)&&role!=='professional')setProfessionalId(requested)},[searchParams,professionals,role])
 useEffect(()=>{if(!business||!professionalId){setProHours(defaultHours());return}(async()=>{const{data}=await supabase.from('professional_hours').select('*').eq('business_id',business.id).eq('professional_id',professionalId).order('day_of_week');setProHours(data?.length?mergeHours(data as WeeklyHour[]):businessHours.map(x=>({...x,id:undefined})))})()},[business,professionalId,businessHours])
 function updateHours(setter:(v:WeeklyHour[])=>void,list:WeeklyHour[],day:number,key:'is_open'|'open_time'|'close_time',value:boolean|string){setter(list.map(x=>x.day_of_week===day?{...x,[key]:value}:x))}
 async function saveBusinessHours(){if(!business)return;const rows=businessHours.map(x=>({business_id:business.id,day_of_week:x.day_of_week,is_open:x.is_open,open_time:x.open_time,close_time:x.close_time}));const{error}=await supabase.from('business_hours').upsert(rows,{onConflict:'business_id,day_of_week'});setMessage(error?error.message:'Horários da empresa atualizados.');load()}
 async function saveProHours(){if(!business||!professionalId)return;const rows=proHours.map(x=>({business_id:business.id,professional_id:professionalId,day_of_week:x.day_of_week,is_open:x.is_open,open_time:x.open_time,close_time:x.close_time}));const{error}=await supabase.from('professional_hours').upsert(rows,{onConflict:'professional_id,day_of_week'});setMessage(error?error.message:'Jornada do profissional atualizada.')}
 async function addBlock(e:FormEvent){e.preventDefault();if(!business||!block.start_date||!block.end_date||!block.reason.trim())return setMessage('Informe período e motivo do bloqueio.');const payload={business_id:business.id,professional_id:block.professional_id||null,start_date:block.start_date,end_date:block.end_date,start_time:block.start_time||null,end_time:block.end_time||null,reason:block.reason.trim()};const{error}=await supabase.from('schedule_blocks').insert(payload);if(error)return setMessage(error.message);setBlock({professional_id:'',start_date:'',end_date:'',start_time:'',end_time:'',reason:''});setMessage('Bloqueio criado.');load()}
 async function removeBlock(id:string){if(!confirm('Remover este bloqueio?'))return;await supabase.from('schedule_blocks').delete().eq('id',id);load()}
 if(!business)return <div className="center-screen">Carregando disponibilidade...</div>
 const canEditHours=['owner','manager'].includes(role); const canBlock=role!=='professional'||!!linkedProfessionalId
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="availability"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">AGENDA AVANÇADA</span><h1>Disponibilidade</h1><div className="live-row"><span className={`live-badge ${live?'online':'connecting'}`}><Radio size={14}/>{live?'Sincronizado':'Conectando...'}</span></div></div></div>{message&&<div className="crm-feedback"><span>{message}</span><button onClick={()=>setMessage('')}><X size={15}/></button></div>}
 <div className="advanced-grid-2"><section className="panel-card"><div className="panel-title"><div><Clock3/><h2>Horário semanal da empresa</h2></div><button className="button button-secondary" disabled={!canEditHours} onClick={saveBusinessHours}><Save size={15}/>Salvar</button></div><HoursEditor list={businessHours} setList={setBusinessHours} update={updateHours}/></section>
 <section className="panel-card"><div className="panel-title"><div><Clock3/><h2>Jornada por profissional</h2></div><button className="button button-secondary" disabled={!professionalId||!canEditHours} onClick={saveProHours}><Save size={15}/>Salvar</button></div><select className="input" value={professionalId} disabled={role==='professional'} onChange={e=>setProfessionalId(e.target.value)}><option value="">Selecione um profissional</option>{professionals.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>{professionalId?<HoursEditor list={proHours} setList={setProHours} update={updateHours}/>:<p className="empty-inline">Selecione um profissional para configurar horários próprios.</p>}</section></div>
 <div className="advanced-grid-2"><section className="panel-card"><div className="panel-title"><div><CalendarOff/><h2>Bloqueios futuros</h2></div></div>{blocks.map(b=><div className="compact-row" key={b.id}><div><b>{b.reason}</b><small>{b.start_date.split('-').reverse().join('/')} até {b.end_date.split('-').reverse().join('/')} {b.start_time?`• ${b.start_time.slice(0,5)}–${b.end_time?.slice(0,5)}`:'• dia inteiro'} {b.professionals?.name?`• ${b.professionals.name}`:'• toda equipe'}</small></div><button className="icon-action danger-action" onClick={()=>removeBlock(b.id)}><Trash2 size={15}/></button></div>)}{!blocks.length&&<p className="empty-inline">Nenhum bloqueio futuro.</p>}</section>
 <form className="crud-form-card" onSubmit={addBlock}><span className="eyebrow">BLOQUEAR AGENDA</span><h2>Folga, feriado ou compromisso</h2><label>Aplicar a<select className="input" value={block.professional_id} disabled={role==='professional'} onChange={e=>setBlock({...block,professional_id:e.target.value})}>{role!=='professional'&&<option value="">Toda a equipe</option>}{professionals.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="form-grid"><label>Data inicial<input className="input" type="date" value={block.start_date} onChange={e=>setBlock({...block,start_date:e.target.value,end_date:block.end_date||e.target.value})}/></label><label>Data final<input className="input" type="date" min={block.start_date} value={block.end_date} onChange={e=>setBlock({...block,end_date:e.target.value})}/></label><label>Hora inicial<input className="input" type="time" value={block.start_time} onChange={e=>setBlock({...block,start_time:e.target.value})}/></label><label>Hora final<input className="input" type="time" value={block.end_time} onChange={e=>setBlock({...block,end_time:e.target.value})}/></label></div><label>Motivo<input className="input" value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})} placeholder="Ex.: feriado, almoço especial, férias"/></label><button className="button button-primary full" disabled={!canBlock}><Plus size={16}/>Criar bloqueio</button></form></div>
 </section></main>}
function mergeHours(rows:WeeklyHour[]){const base=defaultHours();return base.map(x=>({...x,...rows.find(r=>r.day_of_week===x.day_of_week)}))}
function HoursEditor({list,setList,update}:{list:WeeklyHour[];setList:(v:WeeklyHour[])=>void;update:(setter:(v:WeeklyHour[])=>void,list:WeeklyHour[],day:number,key:'is_open'|'open_time'|'close_time',value:boolean|string)=>void}){return <div className="hours-list">{list.map(h=><div className="hours-row" key={h.day_of_week}><label className="switch-row"><input type="checkbox" checked={h.is_open} onChange={e=>update(setList,list,h.day_of_week,'is_open',e.target.checked)}/><span>{days[h.day_of_week]}</span></label>{h.is_open?<div><input className="input" type="time" value={h.open_time} onChange={e=>update(setList,list,h.day_of_week,'open_time',e.target.value)}/><span>até</span><input className="input" type="time" value={h.close_time} onChange={e=>update(setList,list,h.day_of_week,'close_time',e.target.value)}/></div>:<small>Fechado</small>}</div>)}</div>}
