import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowDownCircle, ArrowUpCircle, CircleDollarSign, Plus, Radio, Save, Trash2, WalletCards, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business, FinancialTransaction } from '../types'
const iso=(d=new Date())=>{const z=d.getTimezoneOffset();return new Date(d.getTime()-z*60000).toISOString().slice(0,10)};const start=()=>iso(new Date(new Date().getFullYear(),new Date().getMonth(),1));const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function FinancePage(){
 const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[role,setRole]=useState('professional');const[items,setItems]=useState<FinancialTransaction[]>([]);const[serviceRevenue,setServiceRevenue]=useState(0);const[commission,setCommission]=useState(0);const[live,setLive]=useState(false);const[message,setMessage]=useState('');const[form,setForm]=useState({type:'expense',category:'Operacional',description:'',amount:'',payment_method:'pix',status:'paid',transaction_date:iso()})
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setRole(m.role);const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b)})()},[navigate])
 const load=useCallback(async()=>{if(!business)return;const [{data:t},{data:a}]=await Promise.all([supabase.from('financial_transactions').select('*').eq('business_id',business.id).gte('transaction_date',start()).lte('transaction_date',iso(new Date(new Date().getFullYear(),new Date().getMonth()+1,0))).order('transaction_date',{ascending:false}).order('created_at',{ascending:false}),supabase.from('appointments').select('final_amount,discount_amount,status,services(price),professionals(commission_percent)').eq('business_id',business.id).eq('status','completed').gte('appointment_date',start())]);setItems((t||[]) as FinancialTransaction[]);let rev=0,com=0;(a||[]).forEach((r:any)=>{const value=Number(r.final_amount??(Number(r.services?.price||0)-Number(r.discount_amount||0)));rev+=value;com+=value*Number(r.professionals?.commission_percent||0)/100});setServiceRevenue(rev);setCommission(com)},[business])
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!business)return;const ch=supabase.channel(`finance:${business.id}`).on('postgres_changes',{event:'*',schema:'public',table:'financial_transactions',filter:`business_id=eq.${business.id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'appointments',filter:`business_id=eq.${business.id}`},load).subscribe(s=>setLive(s==='SUBSCRIBED'));return()=>{supabase.removeChannel(ch)}},[business,load])
 const income=useMemo(()=>items.filter(x=>x.type==='income'&&x.status==='paid').reduce((s,x)=>s+Number(x.amount),0),[items]);const expenses=useMemo(()=>items.filter(x=>x.type==='expense'&&x.status==='paid').reduce((s,x)=>s+Number(x.amount),0),[items]);const result=serviceRevenue+income-expenses-commission
 async function save(e:FormEvent){e.preventDefault();if(!business||!form.description.trim()||Number(form.amount)<=0)return setMessage('Preencha descrição e valor válido.');const{error}=await supabase.from('financial_transactions').insert({...form,business_id:business.id,amount:Number(form.amount)});if(error)return setMessage(error.message);setForm(v=>({...v,description:'',amount:''}));setMessage('Lançamento salvo.');load()}
 async function remove(id:string){if(!confirm('Excluir este lançamento financeiro?'))return;const{error}=await supabase.from('financial_transactions').delete().eq('id',id);if(error)setMessage(error.message);else load()}
 if(!business)return <div className="center-screen">Carregando financeiro...</div>
 if(!['owner','manager'].includes(role))return <main className="admin-page"><AdminSidebar businessName={business.name} current="finance"/><section className="admin-content advanced-page"><section className="panel-card"><h2>Acesso restrito</h2><p>O módulo financeiro é exclusivo para proprietário e gerente.</p></section></section></main>
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="finance"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">GESTÃO FINANCEIRA</span><h1>Financeiro</h1><div className="live-row"><span className={`live-badge ${live?'online':'connecting'}`}><Radio size={14}/>{live?'Tempo real ativo':'Conectando...'}</span></div></div></div>{message&&<div className="crm-feedback"><span>{message}</span><button onClick={()=>setMessage('')}><X size={15}/></button></div>}
 <div className="advanced-kpis"><article><ArrowUpCircle/><small>Serviços concluídos</small><strong>{brl(serviceRevenue)}</strong><span>Receita operacional</span></article><article><CircleDollarSign/><small>Outras entradas</small><strong>{brl(income)}</strong><span>Lançamentos manuais</span></article><article><ArrowDownCircle/><small>Despesas + comissões</small><strong>{brl(expenses+commission)}</strong><span>Comissões: {brl(commission)}</span></article><article><WalletCards/><small>Resultado estimado</small><strong>{brl(result)}</strong><span>Mês atual</span></article></div>
 <div className="advanced-grid-2 finance-layout"><section className="panel-card"><div className="panel-title"><div><CircleDollarSign/><h2>Fluxo do mês</h2></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Forma</th><th>Valor</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.transaction_date.split('-').reverse().join('/')}</td><td><span className={`finance-type ${x.type}`}>{x.type==='income'?'Entrada':'Saída'}</span></td><td><strong>{x.description}</strong><small>{x.category}</small></td><td>{x.payment_method||'—'}</td><td><strong>{brl(Number(x.amount))}</strong></td><td><button className="icon-action danger-action" onClick={()=>remove(x.id)}><Trash2 size={15}/></button></td></tr>)}{!items.length&&<tr><td colSpan={6} className="empty-row">Nenhum lançamento manual neste mês.</td></tr>}</tbody></table></div></section>
 <form className="crud-form-card" onSubmit={save}><span className="eyebrow">NOVO LANÇAMENTO</span><h2>Registrar movimentação</h2><label>Tipo<select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="expense">Despesa</option><option value="income">Entrada extra</option></select></label><label>Categoria<input className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Descrição<input className="input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Valor<input className="input" type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Forma<select className="input" value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option><option value="bank_transfer">Transferência</option><option value="other">Outro</option></select></label><label>Data<input className="input" type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label><button className="button button-primary full"><Save size={16}/>Salvar lançamento</button></form></div>
 </section></main>
}
