import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Boxes, CircleDollarSign, Minus, PackagePlus, Plus, Radio, Save, Trash2, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business, InventoryProduct } from '../types'
const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const blank={name:'',sku:'',unit:'un',stock_quantity:'0',min_stock:'0',cost_price:'0',sale_price:'0'}
export function InventoryPage(){
 const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[role,setRole]=useState('');const[items,setItems]=useState<InventoryProduct[]>([]);const[live,setLive]=useState(false);const[message,setMessage]=useState('');const[editing,setEditing]=useState<string|null>(null);const[form,setForm]=useState(blank)
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setRole(m.role);const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b)})()},[navigate])
 const load=useCallback(async()=>{if(!business)return;const{data,error}=await supabase.from('inventory_products').select('*').eq('business_id',business.id).order('name');if(error)setMessage(error.message);else setItems((data||[]) as InventoryProduct[])},[business])
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!business)return;const ch=supabase.channel(`inventory:${business.id}`).on('postgres_changes',{event:'*',schema:'public',table:'inventory_products',filter:`business_id=eq.${business.id}`},load).subscribe(s=>setLive(s==='SUBSCRIBED'));return()=>{supabase.removeChannel(ch)}},[business,load])
 async function save(e:FormEvent){e.preventDefault();if(!business||!form.name.trim())return setMessage('Informe o nome do item.');const payload={business_id:business.id,name:form.name.trim(),sku:form.sku.trim()||null,unit:form.unit,stock_quantity:Number(form.stock_quantity),min_stock:Number(form.min_stock),cost_price:Number(form.cost_price),sale_price:Number(form.sale_price),active:true};const q=editing?supabase.from('inventory_products').update(payload).eq('id',editing):supabase.from('inventory_products').insert(payload);const{error}=await q;if(error)return setMessage(error.message);setEditing(null);setForm(blank);setMessage(editing?'Item atualizado.':'Item cadastrado.');await load()}
 function edit(x:InventoryProduct){setEditing(x.id);setForm({name:x.name,sku:x.sku||'',unit:x.unit,stock_quantity:String(x.stock_quantity),min_stock:String(x.min_stock),cost_price:String(x.cost_price),sale_price:String(x.sale_price)})}
 async function adjust(id:string,delta:number){const{error}=await supabase.rpc('adjust_inventory_stock',{p_product_id:id,p_delta:delta,p_reason:delta>0?'Ajuste de entrada':'Ajuste de saída'});if(error)setMessage(error.message);else await load()}
 async function remove(id:string){if(!confirm('Excluir este item do estoque?'))return;const{error}=await supabase.from('inventory_products').delete().eq('id',id);if(error)setMessage(error.message);else await load()}
 const low=useMemo(()=>items.filter(x=>x.active&&Number(x.stock_quantity)<=Number(x.min_stock)),[items]);const value=items.reduce((s,x)=>s+Number(x.stock_quantity)*Number(x.cost_price),0);const retail=items.reduce((s,x)=>s+Number(x.stock_quantity)*Number(x.sale_price),0)
 if(!business)return <div className="center-screen">Carregando estoque...</div>;if(!['owner','manager','receptionist'].includes(role))return <main className="admin-page"><AdminSidebar businessName={business.name} current="inventory"/><section className="admin-content advanced-page"><section className="panel-card"><h2>Acesso restrito</h2><p>Estoque está disponível para proprietário, gerente e recepção.</p></section></section></main>
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="inventory"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">CONTROLE OPERACIONAL</span><h1>Estoque</h1><div className="live-row"><span className={`live-badge ${live?'online':'connecting'}`}><Radio size={14}/>{live?'Tempo real ativo':'Conectando...'}</span></div></div></div>{message&&<div className="crm-feedback"><span>{message}</span><button onClick={()=>setMessage('')}><X size={15}/></button></div>}
 <div className="advanced-kpis compact-kpis"><article><Boxes/><small>Itens ativos</small><strong>{items.filter(x=>x.active).length}</strong><span>{items.length} cadastrados</span></article><article><AlertTriangle/><small>Estoque baixo</small><strong>{low.length}</strong><span>no mínimo ou abaixo</span></article><article><CircleDollarSign/><small>Custo em estoque</small><strong>{brl(value)}</strong><span>valor de aquisição</span></article><article><CircleDollarSign/><small>Valor potencial</small><strong>{brl(retail)}</strong><span>preço de venda</span></article></div>
 <div className="advanced-grid-2 inventory-layout"><section className="panel-card"><div className="panel-title"><div><Boxes/><h2>Produtos e consumíveis</h2></div></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Saldo</th><th>Mínimo</th><th>Custo</th><th>Venda</th><th>Ações</th></tr></thead><tbody>{items.map(x=>{const isLow=Number(x.stock_quantity)<=Number(x.min_stock);return <tr key={x.id} className={isLow?'low-stock-row':''}><td><strong>{x.name}</strong><small>{x.sku||'Sem SKU'} • {x.unit}</small></td><td><strong>{Number(x.stock_quantity).toLocaleString('pt-BR')}</strong>{isLow&&<small className="danger-text">Estoque baixo</small>}</td><td>{Number(x.min_stock).toLocaleString('pt-BR')}</td><td>{brl(Number(x.cost_price))}</td><td>{brl(Number(x.sale_price))}</td><td><div className="table-actions"><button className="icon-action" title="Saída de 1" onClick={()=>adjust(x.id,-1)}><Minus size={15}/></button><button className="icon-action success-action" title="Entrada de 1" onClick={()=>adjust(x.id,1)}><Plus size={15}/></button><button className="icon-action" onClick={()=>edit(x)}>Editar</button>{['owner','manager'].includes(role)&&<button className="icon-action danger-action" onClick={()=>remove(x.id)}><Trash2 size={15}/></button>}</div></td></tr>})}{!items.length&&<tr><td colSpan={6} className="empty-row">Nenhum item cadastrado.</td></tr>}</tbody></table></div></section>
 <form className="crud-form-card" onSubmit={save}><span className="eyebrow">{editing?'EDITAR ITEM':'NOVO ITEM'}</span><h2>{editing?'Atualizar estoque':'Cadastrar produto'}</h2><label>Nome<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>SKU / código<input className="input" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>Unidade<select className="input" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value="un">Unidade</option><option value="ml">ml</option><option value="l">Litro</option><option value="g">Grama</option><option value="kg">Kg</option><option value="cx">Caixa</option><option value="pct">Pacote</option></select></label><label>Saldo atual<input className="input" type="number" step="0.01" min="0" value={form.stock_quantity} onChange={e=>setForm({...form,stock_quantity:e.target.value})}/></label><label>Estoque mínimo<input className="input" type="number" step="0.01" min="0" value={form.min_stock} onChange={e=>setForm({...form,min_stock:e.target.value})}/></label><label>Custo unitário<input className="input" type="number" step="0.01" min="0" value={form.cost_price} onChange={e=>setForm({...form,cost_price:e.target.value})}/></label><label>Preço de venda<input className="input" type="number" step="0.01" min="0" value={form.sale_price} onChange={e=>setForm({...form,sale_price:e.target.value})}/></label><div className="form-actions">{editing&&<button type="button" className="button button-secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Cancelar</button>}<button className="button button-primary"><Save size={16}/>{editing?'Salvar alterações':'Cadastrar item'}</button></div></form></div>
 </section></main>
}
