import { useEffect, useState } from 'react'
import { CheckCircle2, LogIn, ShieldCheck } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
export function InvitePage(){const{token}=useParams();const navigate=useNavigate();const[state,setState]=useState<'loading'|'login'|'ready'|'done'|'error'>('loading');const[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getUser();setState(data.user?'ready':'login')})()},[])
 async function accept(){if(!token)return;setState('loading');const{error}=await supabase.rpc('accept_business_invite',{p_token:token});if(error){setMessage(error.message.includes('invite_email_mismatch')?'Este convite pertence a outro e-mail.':error.message.includes('invite_invalid')?'Convite inválido ou expirado.':error.message.includes('user_already_has_business')?'Esta conta já está vinculada a outra empresa. Use uma conta sem empresa para aceitar este convite.':error.message);setState('error');return}setState('done');setTimeout(()=>navigate('/painel/dashboard'),900)}
 if(state==='loading')return <div className="center-screen">Validando convite...</div>
 return <main className="auth-page"><section className="login-card invite-card"><div className="brand"><span className="brand-icon"><ShieldCheck/></span>BarberAgenda</div>{state==='login'?<><h1>Entre para aceitar</h1><p>Faça login ou crie sua conta usando exatamente o e-mail que recebeu o convite.</p><button className="button button-primary full" onClick={()=>navigate(`/login?redirect=/convite/${token}`)}><LogIn size={17}/>Ir para login</button></>:state==='done'?<><CheckCircle2 size={42}/><h1>Acesso liberado</h1><p>Você já faz parte da equipe.</p></>:<><h1>Convite para equipe</h1><p>{state==='error'?message:'Seu usuário será vinculado à empresa com a permissão definida pelo responsável.'}</p><button className="button button-primary full" onClick={accept}>Aceitar convite</button></>}</section></main>}
