import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, Scissors, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Appointment, Business } from '../types'
const iso=(d:Date)=>{const z=d.getTimezoneOffset();return new Date(d.getTime()-z*60000).toISOString().slice(0,10)};const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
type Row=Appointment&{services?:{name:string;price:number}|null;professionals?:{name:string}|null;final_amount?:number|null;discount_amount?:number|null}
export function ReportsPage(){const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[role,setRole]=useState('professional');const[from,setFrom]=useState(iso(new Date(new Date().getFullYear(),new Date().getMonth(),1)));const[to,setTo]=useState(iso(new Date()));const[rows,setRows]=useState<Row[]>([])
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setRole(m.role);const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b)})()},[navigate])
 useEffect(()=>{if(!business)return;(async()=>{const{data}=await supabase.from('appointments').select('*,services(name,price),professionals(name)').eq('business_id',business.id).gte('appointment_date',from).lte('appointment_date',to).order('appointment_date');setRows((data||[]) as Row[])})()},[business,from,to])
 const completed=rows.filter(x=>x.status==='completed');const revenue=completed.reduce((s,x)=>s+Number(x.final_amount??(Number(x.services?.price||0)-Number(x.discount_amount||0))),0);const ticket=completed.length?revenue/completed.length:0;const noShow=rows.filter(x=>x.status==='no_show').length;const cancelled=rows.filter(x=>x.status==='cancelled').length
 const byService=useMemo(()=>group(rows,'service'),[rows]);const byPro=useMemo(()=>group(rows,'professional'),[rows]);function exportCsv(){const header=['Data','Horario','Cliente','Servico','Profissional','Status','Valor'];const lines=rows.map(r=>[r.appointment_date,r.start_time.slice(0,5),r.client_name,r.services?.name||'',r.professionals?.name||'',r.status,String(r.final_amount??r.services?.price??0)]);const csv=[header,...lines].map(a=>a.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`relatorio-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(!business)return <div className="center-screen">Carregando relatórios...</div>;if(!['owner','manager','professional'].includes(role))return <main className="admin-page"><AdminSidebar businessName={business.name} current="reports"/><section className="admin-content advanced-page"><section className="panel-card"><h2>Acesso restrito</h2><p>Relatórios estão disponíveis para proprietário, gerente e profissional vinculado.</p></section></section></main>;return <main className="admin-page"><AdminSidebar businessName={business.name} current="reports"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">ANÁLISE DE PERFORMANCE</span><h1>Relatórios</h1></div><div className="admin-head-actions"><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="button button-secondary" onClick={exportCsv}><Download size={16}/>CSV</button></div></div>
 <div className="advanced-kpis"><article><BarChart3/><small>Faturamento</small><strong>{brl(revenue)}</strong><span>{completed.length} concluídos</span></article><article><BarChart3/><small>Ticket médio</small><strong>{brl(ticket)}</strong><span>por atendimento concluído</span></article><article><BarChart3/><small>Taxa de conclusão</small><strong>{rows.length?Math.round(completed.length/rows.length*100):0}%</strong><span>{rows.length} agendamentos no período</span></article><article><BarChart3/><small>Perdas</small><strong>{noShow+cancelled}</strong><span>{noShow} no-show • {cancelled} cancelados</span></article></div>
 <div className="advanced-grid-2"><Ranking title="Serviços" icon="service" rows={byService}/><Ranking title="Profissionais" icon="professional" rows={byPro}/></div>
 <section className="panel-card"><div className="panel-title"><div><BarChart3/><h2>Resumo de status</h2></div></div><div className="status-summary">{['pending','confirmed','completed','cancelled','no_show'].map(s=><article key={s}><span className={`status status-${s}`}>{s}</span><strong>{rows.filter(r=>r.status===s).length}</strong></article>)}</div></section>
 </section></main>}
function group(rows:Row[],mode:'service'|'professional'){const m=new Map<string,{name:string,count:number,revenue:number}>();rows.filter(x=>x.status==='completed').forEach(r=>{const name=mode==='service'?(r.services?.name||'Sem serviço'):(r.professionals?.name||'Sem profissional');const x=m.get(name)||{name,count:0,revenue:0};x.count++;x.revenue+=Number(r.final_amount ?? r.services?.price ?? 0);m.set(name,x)});return[...m.values()].sort((a,b)=>b.revenue-a.revenue)}
function Ranking({title,icon,rows}:{title:string;icon:'service'|'professional';rows:{name:string;count:number;revenue:number}[]}){const Icon=icon==='service'?Scissors:UserRound;const max=Math.max(1,...rows.map(r=>r.revenue));return <section className="panel-card"><div className="panel-title"><div><Icon/><h2>{title}</h2></div></div>{rows.slice(0,10).map((x,i)=><div className="report-row" key={x.name}><div><span>#{i+1}</span><b>{x.name}</b><small>{x.count} atendimentos</small></div><strong>{brl(x.revenue)}</strong><div className="report-bar"><i style={{width:`${Math.round(x.revenue/max*100)}%`}}/></div></div>)}{!rows.length&&<p className="empty-inline">Sem dados concluídos no período.</p>}</section>}
