import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Headphones, Plus, Radio } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business } from '../types'

type Ticket={id:string;subject:string;message:string;category:string;priority:string;status:string;created_at:string;updated_at:string}
export function SupportCenterPage(){const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[rows,setRows]=useState<Ticket[]>([]);const[subject,setSubject]=useState('');const[message,setMessage]=useState('');const[category,setCategory]=useState('general');const[priority,setPriority]=useState('normal');const[notice,setNotice]=useState('');const[live,setLive]=useState(false)
 useEffect(()=>{void(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user){navigate('/login');return}const{data:m}=await supabase.from('business_members').select('business_id').eq('user_id',u.user.id).limit(1).maybeSingle();if(!m){navigate('/onboarding');return}const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b as Business)})()},[navigate])
 const load=useCallback(async()=>{if(!business)return;const{data,error}=await supabase.from('support_tickets').select('id,subject,message,category,priority,status,created_at,updated_at').eq('business_id',business.id).order('created_at',{ascending:false});if(error){setNotice(error.message);return}setRows((data||[]) as Ticket[])},[business]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!business)return;const ch=supabase.channel(`support:${business.id}`).on('postgres_changes',{event:'*',schema:'public',table:'support_tickets',filter:`business_id=eq.${business.id}`},load).subscribe(s=>setLive(s==='SUBSCRIBED'));return()=>{void supabase.removeChannel(ch)}},[business,load])
 async function create(e:FormEvent){e.preventDefault();if(!business)return;const{data:u}=await supabase.auth.getUser();if(!u.user)return;const{error}=await supabase.from('support_tickets').insert({business_id:business.id,created_by:u.user.id,subject:subject.trim(),message:message.trim(),category,priority});setNotice(error?error.message:'Chamado enviado para o suporte.');if(!error){setSubject('');setMessage('');setCategory('general');setPriority('normal');void load()}}
 if(!business)return <div className="center-screen">Carregando suporte...</div>
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="support"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">ATENDIMENTO</span><h1>Central de Suporte</h1><div className="live-row"><span className={`live-badge ${live?'online':'connecting'}`}><Radio size={14}/>{live?'Tickets ao vivo':'Conectando...'}</span></div></div></div>{notice&&<div className="notice">{notice}</div>}<div className="advanced-grid-2"><form className="panel-card crud-form" onSubmit={create}><div className="panel-title"><div><Headphones/><h2>Abrir chamado</h2></div></div><label>Assunto<input className="input" value={subject} onChange={e=>setSubject(e.target.value)} required maxLength={160}/></label><div className="form-grid"><label>Categoria<select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="general">Geral</option><option value="technical">Erro técnico</option><option value="billing">Financeiro</option><option value="feature">Sugestão</option></select></label><label>Prioridade<select className="input" value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div><label>Mensagem<textarea className="input" rows={7} value={message} onChange={e=>setMessage(e.target.value)} required/></label><button className="button button-primary"><Plus size={16}/>Enviar chamado</button></form><section className="panel-card"><div className="panel-title"><div><Headphones/><h2>Meus chamados</h2></div><span>{rows.length}</span></div>{rows.map(t=><article className="support-ticket-row" key={t.id}><div><b>{t.subject}</b><small>{t.category} • {new Date(t.created_at).toLocaleString('pt-BR')}</small><p>{t.message}</p></div><span className={`status status-${t.status==='resolved'?'completed':t.status==='closed'?'cancelled':'confirmed'}`}>{t.status.replace('_',' ')}</span></article>)}{!rows.length&&<p className="empty-inline">Nenhum chamado aberto ainda.</p>}</section></div></section></main>}
