import { useEffect, useState } from 'react'
import { CheckCircle2, Database, RefreshCw, ShieldAlert, XCircle } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business, SchemaHealthItem } from '../types'
export function SystemCheckPage(){const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[role,setRole]=useState('');const[items,setItems]=useState<SchemaHealthItem[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setRole(m.role);const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b);await run();setLoading(false)})()},[navigate])
 async function run(){setLoading(true);setMessage('');const{data,error}=await supabase.rpc('app_schema_health');if(error){setMessage(`Não foi possível executar o diagnóstico: ${error.message}. Execute supabase/MASTER_PRODUCTION_UPGRADE.sql no SQL Editor.`);setItems([])}else setItems((data||[]) as SchemaHealthItem[]);setLoading(false)}
 const ok=items.filter(x=>x.status==='OK').length,missing=items.filter(x=>x.status!=='OK').length
 if(!business)return <div className="center-screen">Carregando diagnóstico...</div>;if(!['owner','manager'].includes(role))return <main className="admin-page"><AdminSidebar businessName={business.name} current="diagnostics"/><section className="admin-content advanced-page"><section className="panel-card"><h2>Acesso restrito</h2><p>O diagnóstico técnico é exclusivo para proprietário e gerente.</p></section></section></main>
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="diagnostics"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">SAÚDE TÉCNICA</span><h1>Diagnóstico do sistema</h1><p className="muted">Verifica tabelas, colunas, RPCs e módulos que o BarberAgenda utiliza.</p></div><button className="button button-secondary" onClick={run} disabled={loading}><RefreshCw size={16}/>{loading?'Verificando...':'Verificar novamente'}</button></div>{message&&<div className="notice danger-notice">{message}</div>}
 <div className="advanced-kpis compact-kpis"><article><Database/><small>Itens verificados</small><strong>{items.length}</strong><span>estrutura do banco</span></article><article><CheckCircle2/><small>OK</small><strong>{ok}</strong><span>prontos para uso</span></article><article><ShieldAlert/><small>Pendências</small><strong>{missing}</strong><span>{missing?'exigem correção':'nenhuma encontrada'}</span></article><article><Database/><small>Versão esperada</small><strong>4.0</strong><span>Enterprise</span></article></div>
 <section className="panel-card"><div className="panel-title"><div><Database/><h2>Checklist do Supabase</h2></div></div><div className="schema-health-list">{items.map(x=><article key={`${x.category}-${x.check_name}`} className={x.status==='OK'?'schema-ok':'schema-error'}>{x.status==='OK'?<CheckCircle2/>:<XCircle/>}<div><strong>{x.check_name}</strong><small>{x.category} • {x.detail}</small></div><span>{x.status}</span></article>)}{!items.length&&!loading&&<p className="empty-inline">Nenhum resultado retornado.</p>}</div></section>
 {missing>0&&<section className="panel-card repair-card"><h2>Como corrigir</h2><p>Execute o arquivo <code>supabase/MASTER_PRODUCTION_UPGRADE.sql</code> no Supabase → SQL Editor. O arquivo é idempotente e foi preparado para atualizar bancos existentes sem apagar clientes ou agendamentos.</p></section>}
 </section></main>}
