import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Copy, Link2, Mail, Plus, Save, ShieldCheck, Trash2, UserCog, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business, BusinessInvite, BusinessMember, Professional } from '../types'
export function TeamPage(){const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[currentUser,setCurrentUser]=useState('');const[currentRole,setCurrentRole]=useState('professional');const[members,setMembers]=useState<BusinessMember[]>([]);const[professionals,setProfessionals]=useState<Professional[]>([]);const[invites,setInvites]=useState<BusinessInvite[]>([]);const[message,setMessage]=useState('');const[form,setForm]=useState({email:'',role:'receptionist'})
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');setCurrentUser(u.user.id);const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setCurrentRole(m.role);const{data:b}=await supabase.from('businesses').select('*').eq('id',m.business_id).single();setBusiness(b)})()},[navigate])
 const load=useCallback(async()=>{if(!business)return;const[{data:m},{data:i},{data:p}]=await Promise.all([supabase.from('business_members').select('*').eq('business_id',business.id).order('created_at'),supabase.from('business_invites').select('*').eq('business_id',business.id).eq('status','pending').order('created_at',{ascending:false}),supabase.from('professionals').select('*').eq('business_id',business.id).eq('active',true).order('name')]);setProfessionals((p||[]) as Professional[]);setMembers((m||[]) as BusinessMember[]);setInvites((i||[]) as BusinessInvite[])},[business]);useEffect(()=>{load()},[load])
 async function invite(e:FormEvent){e.preventDefault();if(!business||!form.email.includes('@'))return setMessage('Informe um e-mail válido.');const token=crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,'');const{error}=await supabase.from('business_invites').insert({business_id:business.id,email:form.email.trim().toLowerCase(),role:form.role,token});if(error)return setMessage(error.code==='23505'?'Já existe um convite pendente para este e-mail.':error.message);setForm({...form,email:''});setMessage('Convite criado. Copie o link e envie à pessoa.');load()}
 async function updateMember(id:string,role:string,active:boolean,professional_id?:string|null){const{error}=await supabase.from('business_members').update({role,active,professional_id:role==='professional'?(professional_id||null):null}).eq('id',id).eq('business_id',business?.id);if(error)setMessage(error.message);else load()}
 async function removeMember(m:BusinessMember){if(m.user_id===currentUser)return setMessage('Você não pode remover seu próprio acesso por esta tela.');if(!confirm('Remover este membro da empresa?'))return;const{error}=await supabase.from('business_members').delete().eq('id',m.id);if(error)setMessage(error.message);else load()}
 async function cancelInvite(id:string){await supabase.from('business_invites').update({status:'cancelled'}).eq('id',id);load()}
 if(!business)return <div className="center-screen">Carregando equipe...</div>;const canManage=['owner','manager'].includes(currentRole)
 if(!canManage)return <main className="admin-page"><AdminSidebar businessName={business.name} current="team"/><section className="admin-content advanced-page"><section className="panel-card"><h2>Acesso restrito</h2><p>Somente proprietário e gerente podem administrar a equipe.</p></section></section></main>
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="team"/><section className="admin-content advanced-page"><div className="admin-head"><div><span className="eyebrow">CONTROLE DE ACESSO</span><h1>Equipe e permissões</h1></div></div>{message&&<div className="crm-feedback"><span>{message}</span><button onClick={()=>setMessage('')}><X size={15}/></button></div>}
 <section className="panel-card"><div className="panel-title"><div><ShieldCheck/><h2>Membros</h2></div><span>{members.length} acessos</span></div><div className="table-wrap"><table><thead><tr><th>Membro</th><th>Função</th><th>Profissional vinculado</th><th>Status</th><th>Ações</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><strong>{m.display_name||`Usuário ${m.user_id.slice(0,8)}`}</strong><small>{m.user_id===currentUser?'Você':''}</small></td><td><select className="input table-input" value={m.role} disabled={!canManage||m.role==='owner'} onChange={e=>updateMember(m.id,e.target.value,m.active,m.professional_id)}><option value="owner">Proprietário</option><option value="manager">Gerente</option><option value="receptionist">Recepção</option><option value="professional">Profissional</option></select></td><td>{m.role==='professional'?<select className="input table-input" value={m.professional_id||''} disabled={!canManage} onChange={e=>updateMember(m.id,m.role,m.active,e.target.value||null)}><option value="">Não vinculado</option>{professionals.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:<span className="muted">—</span>}</td><td><button disabled={!canManage||m.role==='owner'} className={`crud-status ${m.active?'active':'inactive'}`} onClick={()=>updateMember(m.id,m.role,!m.active,m.professional_id)}>{m.active?'Ativo':'Inativo'}</button></td><td><button disabled={!canManage||m.role==='owner'||m.user_id===currentUser} className="icon-action danger-action" onClick={()=>removeMember(m)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></section>
 {canManage&&<div className="advanced-grid-2"><form className="crud-form-card" onSubmit={invite}><span className="eyebrow">CONVIDAR</span><h2>Novo acesso</h2><label>E-mail<input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="pessoa@email.com"/></label><label>Função<select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="manager">Gerente</option><option value="receptionist">Recepção</option><option value="professional">Profissional</option></select></label><button className="button button-primary full"><Plus size={16}/>Gerar convite</button><small className="field-hint">O convite expira em 7 dias e só pode ser aceito pelo e-mail informado.</small></form>
 <section className="panel-card"><div className="panel-title"><div><Mail/><h2>Convites pendentes</h2></div></div>{invites.map(i=>{const link=`${window.location.origin}/convite/${i.token}`;return <div className="invite-row" key={i.id}><div><b>{i.email}</b><small>{i.role} • expira {new Date(i.expires_at).toLocaleDateString('pt-BR')}</small></div><div><button className="icon-action" onClick={()=>navigator.clipboard.writeText(link)} title="Copiar link"><Copy size={15}/></button><button className="icon-action danger-action" onClick={()=>cancelInvite(i.id)}><X size={15}/></button></div></div>})}{!invites.length&&<p className="empty-inline">Nenhum convite pendente.</p>}</section></div>}
 </section></main>}
