import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarClock, CheckCircle2, Clock3, Plus, Radio, RefreshCw, Trash2, UserRound, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AdminSidebar } from '../components/AdminSidebar'
import { supabase } from '../lib/supabase'
import type { Business, Professional, Service, WaitlistEntry } from '../types'

const today=()=>{const d=new Date();const z=d.getTimezoneOffset();return new Date(d.getTime()-z*60000).toISOString().slice(0,10)}
const fmt=(v:string)=>v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'—'

type Row=WaitlistEntry & {services?:{name:string}|null;professionals?:{name:string}|null}
export function WaitlistPage(){
 const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null);const[role,setRole]=useState('professional');const[rows,setRows]=useState<Row[]>([]);const[services,setServices]=useState<Service[]>([]);const[professionals,setProfessionals]=useState<Professional[]>([]);const[live,setLive]=useState(false);const[message,setMessage]=useState('');const[loading,setLoading]=useState(true)
 const[form,setForm]=useState({client_name:'',client_phone:'',service_id:'',professional_id:'',desired_date:today(),preferred_period:'any',notes:''})
 useEffect(()=>{(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return navigate('/login');const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',u.user.id).maybeSingle();if(!m)return navigate('/onboarding');setRole(m.role);const[{data:b},{data:s},{data:p}]=await Promise.all([supabase.from('businesses').select('*').eq('id',m.business_id).single(),supabase.from('services').select('*').eq('business_id',m.business_id).eq('active',true).order('name'),supabase.from('professionals').select('*').eq('business_id',m.business_id).eq('active',true).order('name')]);setBusiness(b);setServices(s||[]);setProfessionals(p||[]);setLoading(false)})()},[navigate])
 const load=useCallback(async()=>{if(!business)return;const{data,error}=await supabase.from('waitlist_entries').select('*,services(name),professionals(name)').eq('business_id',business.id).order('desired_date').order('created_at');if(error)setMessage(error.message);else setRows((data||[]) as Row[])},[business])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!business)return;const ch=supabase.channel(`waitlist:${business.id}`).on('postgres_changes',{event:'*',schema:'public',table:'waitlist_entries',filter:`business_id=eq.${business.id}`},load).subscribe(s=>setLive(s==='SUBSCRIBED'));return()=>{supabase.removeChannel(ch)}},[business,load])
 async function create(e:FormEvent){e.preventDefault();if(!business||!form.client_name.trim()||!form.client_phone.trim()||!form.service_id)return setMessage('Informe cliente, telefone e serviço.');const{error}=await supabase.from('waitlist_entries').insert({business_id:business.id,client_name:form.client_name.trim(),client_phone:form.client_phone.trim(),service_id:form.service_id,professional_id:form.professional_id||null,desired_date:form.desired_date,preferred_period:form.preferred_period,notes:form.notes.trim()||null,status:'waiting',source:'staff'});if(error)return setMessage(`Não foi possível adicionar: ${error.message}`);setForm({client_name:'',client_phone:'',service_id:'',professional_id:'',desired_date:today(),preferred_period:'any',notes:''});setMessage('Cliente adicionado à lista de espera.');await load()}
 async function status(id:string,status:WaitlistEntry['status']){const{error}=await supabase.from('waitlist_entries').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)setMessage(error.message);else await load()}
 async function remove(id:string){if(!confirm('Excluir este registro da lista de espera?'))return;const{error}=await supabase.from('waitlist_entries').delete().eq('id',id);if(error)setMessage(error.message);else await load()}
 const waiting=useMemo(()=>rows.filter(x=>x.status==='waiting'),[rows]);const contacted=rows.filter(x=>x.status==='contacted').length;const booked=rows.filter(x=>x.status==='booked').length;const todayCount=waiting.filter(x=>x.desired_date===today()).length
 if(loading)return <div className="center-screen">Carregando lista de espera...</div>;if(!business)return null
 return <main className="admin-page"><AdminSidebar businessName={business.name} current="waitlist"/><section className="admin-content advanced-page">
  <div className="admin-head"><div><span className="eyebrow">OCUPAÇÃO E OPORTUNIDADES</span><h1>Lista de espera</h1><div className="live-row"><span className={`live-badge ${live?'online':'connecting'}`}><Radio size={14}/>{live?'Tempo real ativo':'Conectando...'}</span></div></div><button className="button button-secondary" onClick={load}><RefreshCw size={16}/>Atualizar</button></div>
  {message&&<div className="crm-feedback"><span>{message}</span><button onClick={()=>setMessage('')}><X size={15}/></button></div>}
  <div className="advanced-kpis compact-kpis"><article><CalendarClock/><small>Aguardando</small><strong>{waiting.length}</strong><span>{todayCount} para hoje</span></article><article><Clock3/><small>Contatados</small><strong>{contacted}</strong><span>aguardando retorno</span></article><article><CheckCircle2/><small>Convertidos</small><strong>{booked}</strong><span>viraram agendamento</span></article><article><UserRound/><small>Total</small><strong>{rows.length}</strong><span>histórico da lista</span></article></div>
  <div className="advanced-grid-2 waitlist-layout"><section className="panel-card"><div className="panel-title"><div><CalendarClock/><h2>Fila atual</h2></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Preferência</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{fmt(x.desired_date)}</strong><small>{x.preferred_period==='any'?'Qualquer horário':x.preferred_period}</small></td><td><strong>{x.client_name}</strong><small>{x.client_phone}</small></td><td><strong>{x.services?.name||'—'}</strong><small>{x.professionals?.name||'Qualquer profissional'}</small></td><td><span className={`status status-${x.status}`}>{x.status}</span></td><td><div className="table-actions">{x.status==='waiting'&&<button className="icon-action" title="Marcar como contatado" onClick={()=>status(x.id,'contacted')}><Clock3 size={15}/></button>}{['waiting','contacted'].includes(x.status)&&<button className="icon-action success-action" title="Marcar como agendado" onClick={()=>status(x.id,'booked')}><CheckCircle2 size={15}/></button>}{x.status!=='cancelled'&&<button className="icon-action" title="Cancelar" onClick={()=>status(x.id,'cancelled')}><X size={15}/></button>}{['owner','manager','receptionist'].includes(role)&&<button className="icon-action danger-action" title="Excluir" onClick={()=>remove(x.id)}><Trash2 size={15}/></button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={5} className="empty-row">Nenhum cliente na lista de espera.</td></tr>}</tbody></table></div></section>
  <form className="crud-form-card" onSubmit={create}><span className="eyebrow">NOVO REGISTRO</span><h2>Adicionar à espera</h2><label>Cliente<input className="input" value={form.client_name} onChange={e=>setForm({...form,client_name:e.target.value})}/></label><label>Telefone<input className="input" value={form.client_phone} onChange={e=>setForm({...form,client_phone:e.target.value})}/></label><label>Serviço<select className="input" value={form.service_id} onChange={e=>setForm({...form,service_id:e.target.value})}><option value="">Selecione</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Profissional<select className="input" value={form.professional_id} onChange={e=>setForm({...form,professional_id:e.target.value})}><option value="">Qualquer profissional</option>{professionals.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Data desejada<input className="input" type="date" min={today()} value={form.desired_date} onChange={e=>setForm({...form,desired_date:e.target.value})}/></label><label>Período<select className="input" value={form.preferred_period} onChange={e=>setForm({...form,preferred_period:e.target.value})}><option value="any">Qualquer horário</option><option value="morning">Manhã</option><option value="afternoon">Tarde</option><option value="evening">Noite</option></select></label><label>Observações<textarea className="input textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="button button-primary full"><Plus size={16}/>Adicionar à lista</button></form></div>
 </section></main>
}
