import { useEffect, useMemo, useState } from 'react'
import { Download, FileSearch, RefreshCcw, Search, ShieldCheck, X } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { dateTime, downloadCsv, jsonText } from './devUtils'

type DevLog={id:string;action:string;target_type:string|null;target_id:string|null;metadata:Record<string,unknown>;created_at:string;actor_user_id:string|null}
type BizLog={id:string;business_id:string;table_name:string;action:string;record_id:string|null;created_at:string;actor_user_id:string|null;old_data:Record<string,unknown>|null;new_data:Record<string,unknown>|null}
type Unified={id:string;source:'dev'|'business';action:string;target:string;targetId:string|null;actor:string|null;businessId:string|null;created_at:string;metadata:unknown;oldData?:unknown;newData?:unknown}

type Range='24h'|'7d'|'30d'|'all'
export function DevAuditPage(){
  const[dev,setDev]=useState<DevLog[]>([]);const[biz,setBiz]=useState<BizLog[]>([]);const[source,setSource]=useState<'all'|'dev'|'business'>('all');const[range,setRange]=useState<Range>('7d');const[action,setAction]=useState('all');const[q,setQ]=useState('');const[msg,setMsg]=useState('');const[selected,setSelected]=useState<Unified|null>(null);const[loading,setLoading]=useState(false)
  async function load(){setLoading(true);setMsg('');const[{data:d,error:de},{data:b,error:be}]=await Promise.all([supabase.from('developer_audit_logs').select('*').order('created_at',{ascending:false}).limit(1000),supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(1000)]);setDev((d||[]) as DevLog[]);setBiz((b||[]) as BizLog[]);if(de||be)setMsg(de?.message||be?.message||'Erro ao carregar auditoria.');setLoading(false)}useEffect(()=>{void load()},[])
  const unified=useMemo<Unified[]>(()=>[
    ...dev.map(x=>({id:x.id,source:'dev' as const,action:x.action,target:x.target_type||'plataforma',targetId:x.target_id,actor:x.actor_user_id,businessId:null,created_at:x.created_at,metadata:x.metadata})),
    ...biz.map(x=>({id:x.id,source:'business' as const,action:x.action,target:x.table_name,targetId:x.record_id,actor:x.actor_user_id,businessId:x.business_id,created_at:x.created_at,metadata:{},oldData:x.old_data,newData:x.new_data}))
  ].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[dev,biz])
  const actions=useMemo(()=>Array.from(new Set(unified.map(x=>x.action))).sort(),[unified])
  const filtered=useMemo(()=>{const threshold=range==='all'?0:Date.now()-(range==='24h'?1:range==='7d'?7:30)*86_400_000;return unified.filter(x=>(source==='all'||x.source===source)&&(action==='all'||x.action===action)&&(!threshold||new Date(x.created_at).getTime()>=threshold)&&(!q.trim()||`${x.action} ${x.target} ${x.targetId||''} ${x.actor||''} ${x.businessId||''}`.toLowerCase().includes(q.toLowerCase())))},[unified,source,action,range,q])
  const stats=useMemo(()=>({total:filtered.length,dev:filtered.filter(x=>x.source==='dev').length,business:filtered.filter(x=>x.source==='business').length,destructive:filtered.filter(x=>['DELETE','developer_admin.disabled','business.status.changed'].some(k=>x.action.includes(k))).length}),[filtered])
  function exportRows(){downloadCsv(`auditoria-${new Date().toISOString().slice(0,10)}.csv`,filtered.map(x=>({origem:x.source,acao:x.action,alvo:x.target,id_alvo:x.targetId,ator:x.actor,empresa:x.businessId,data:x.created_at,metadata:x.metadata,antes:x.oldData,depois:x.newData})))}
  return <>
    <header className="dev-page-head"><div><span className="eyebrow">SEGURANÇA & COMPLIANCE</span><h1>Auditoria</h1><p>Trilha global de ações administrativas e alterações realizadas nas empresas.</p></div><div className="dev-head-actions"><button className="button" onClick={exportRows}><Download size={16}/>Exportar</button><button className="button" onClick={()=>void load()} disabled={loading}><RefreshCcw size={16}/>{loading?'Atualizando...':'Atualizar'}</button></div></header>{msg&&<div className="notice">{msg}</div>}
    <div className="dev-kpis compact"><article><FileSearch/><small>Eventos filtrados</small><strong>{stats.total}</strong><span>na janela selecionada</span></article><article><ShieldCheck/><small>Admin Dev</small><strong>{stats.dev}</strong><span>ações da plataforma</span></article><article><ShieldCheck/><small>Empresas</small><strong>{stats.business}</strong><span>CRUD dos tenants</span></article><article className={stats.destructive?'danger':''}><ShieldCheck/><small>Sensíveis</small><strong>{stats.destructive}</strong><span>eventos destrutivos/críticos</span></article></div>
    <div className="dev-toolbar dev-toolbar-advanced"><div className="search-box"><Search size={17}/><input placeholder="Buscar ação, tabela, usuário ou ID" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={source} onChange={e=>setSource(e.target.value as typeof source)}><option value="all">Todas as origens</option><option value="dev">Admin Dev</option><option value="business">Empresas</option></select><select value={range} onChange={e=>setRange(e.target.value as Range)}><option value="24h">Últimas 24h</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="all">Todo o histórico carregado</option></select><select value={action} onChange={e=>setAction(e.target.value)}><option value="all">Todas as ações</option>{actions.map(x=><option key={x}>{x}</option>)}</select></div>
    <section className="dev-panel"><div className="dev-table-wrap"><table className="dev-table wide"><thead><tr><th>Data</th><th>Origem</th><th>Ação</th><th>Alvo</th><th>ID alvo</th><th>Ator</th><th>Empresa</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={`${x.source}-${x.id}`}><td>{dateTime(x.created_at)}</td><td><span className={`dev-status ${x.source==='dev'?'active':'archived'}`}>{x.source==='dev'?'Admin Dev':'Empresa'}</span></td><td><b>{x.action}</b></td><td>{x.target}</td><td><code>{x.targetId?.slice(0,16)||'—'}</code></td><td><code>{x.actor?.slice(0,16)||'sistema'}</code></td><td><code>{x.businessId?.slice(0,16)||'—'}</code></td><td><button className="dev-table-action" onClick={()=>setSelected(x)}>Detalhes</button></td></tr>)}{!filtered.length&&<tr><td colSpan={8}>Nenhum evento encontrado.</td></tr>}</tbody></table></div></section>
    {selected&&<div className="dev-detail-backdrop" onClick={()=>setSelected(null)}><aside className="dev-detail-drawer dev-detail-wide" onClick={e=>e.stopPropagation()}><div className="dev-detail-head"><div><span className="eyebrow">EVENTO DE AUDITORIA</span><h2>{selected.action}</h2><p>{dateTime(selected.created_at)}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="dev-detail-grid"><div><small>Origem</small><strong>{selected.source}</strong></div><div><small>Alvo</small><strong>{selected.target}</strong></div><div><small>Ator</small><strong>{selected.actor?.slice(0,12)||'sistema'}</strong></div><div><small>Empresa</small><strong>{selected.businessId?.slice(0,12)||'—'}</strong></div></div><section className="dev-detail-section"><h3>Identificadores</h3><dl><div><dt>Evento</dt><dd><code>{selected.id}</code></dd></div><div><dt>Registro</dt><dd><code>{selected.targetId||'—'}</code></dd></div><div><dt>Actor user</dt><dd><code>{selected.actor||'—'}</code></dd></div><div><dt>Business</dt><dd><code>{selected.businessId||'—'}</code></dd></div></dl></section>{selected.source==='business'&&<><section className="dev-detail-section"><h3>Antes</h3><pre className="dev-code-block">{jsonText(selected.oldData)}</pre></section><section className="dev-detail-section"><h3>Depois</h3><pre className="dev-code-block">{jsonText(selected.newData)}</pre></section></>}{selected.source==='dev'&&<section className="dev-detail-section"><h3>Metadata</h3><pre className="dev-code-block">{jsonText(selected.metadata)}</pre></section>}</aside></div>}
  </>
}
