import { useCallback, useEffect, useState } from 'react'
import { Activity, Building2, CalendarCheck, CircleDollarSign, Headphones, ShieldAlert, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

type Stats={businesses_total:number;businesses_active:number;businesses_suspended:number;users_total:number;appointments_today:number;appointments_month:number;gmv_month:number;open_tickets:number;errors_24h:number;active_incidents:number}
type BusinessRow={id:string;name:string;slug:string;platform_status:string;owner_email:string|null;created_at:string;appointment_count:number;plan_name:string|null}
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function DevDashboardPage(){const navigate=useNavigate();const[s,setS]=useState<Stats|null>(null);const[recent,setRecent]=useState<BusinessRow[]>([]);const[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{const[{data:stats},{data:biz}]=await Promise.all([supabase.rpc('dev_admin_dashboard'),supabase.rpc('dev_list_businesses',{p_search:null,p_limit:6,p_offset:0})]);setS((stats||null) as Stats|null);setRecent((biz||[]) as BusinessRow[]);setLoading(false)},[])
 useEffect(()=>{void load();const ch=supabase.channel('dev-dashboard').on('postgres_changes',{event:'*',schema:'public',table:'businesses'},load).on('postgres_changes',{event:'*',schema:'public',table:'support_tickets'},load).subscribe();return()=>{void supabase.removeChannel(ch)}},[load])
 if(loading)return <div className="dev-loading">Carregando visão global...</div>
 return <><header className="dev-page-head"><div><span className="eyebrow">PLATAFORMA</span><h1>Visão global</h1><p>Operação, crescimento e saúde do BarberAgenda.</p></div><span className="dev-live"><Activity size={15}/>Dados globais</span></header>
 <div className="dev-kpis"><article><Building2/><small>Empresas</small><strong>{s?.businesses_total||0}</strong><span>{s?.businesses_suspended||0} suspensas</span></article><article><Users/><small>Usuários</small><strong>{s?.users_total||0}</strong><span>contas Auth</span></article><article><CalendarCheck/><small>Agendamentos hoje</small><strong>{s?.appointments_today||0}</strong><span>{s?.appointments_month||0} no mês</span></article><article><CircleDollarSign/><small>GMV do mês</small><strong>{money(s?.gmv_month||0)}</strong><span>atendimentos concluídos</span></article><article><Headphones/><small>Suporte aberto</small><strong>{s?.open_tickets||0}</strong><span>tickets pendentes</span></article><article className={(s?.errors_24h||0)>0?'danger':''}><ShieldAlert/><small>Erros 24h</small><strong>{s?.errors_24h||0}</strong><span>{s?.active_incidents||0} incidentes ativos</span></article></div>
 <section className="dev-panel"><div className="dev-panel-head"><div><h2>Empresas recentes</h2><p>Últimos tenants cadastrados na plataforma.</p></div><button className="button" onClick={()=>navigate('/dev-admin/empresas')}>Ver todas</button></div><div className="dev-table-wrap"><table className="dev-table"><thead><tr><th>Empresa</th><th>Proprietário</th><th>Status</th><th>Plano</th><th>Agendamentos</th><th>Criada em</th></tr></thead><tbody>{recent.map(b=><tr key={b.id}><td><b>{b.name}</b><small>/{b.slug}</small></td><td>{b.owner_email||'—'}</td><td><span className={`dev-status ${b.platform_status}`}>{b.platform_status}</span></td><td>{b.plan_name||'Sem plano'}</td><td>{b.appointment_count}</td><td>{new Date(b.created_at).toLocaleDateString('pt-BR')}</td></tr>)}{!recent.length&&<tr><td colSpan={6}>Nenhuma empresa cadastrada.</td></tr>}</tbody></table></div></section></>}
