import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Bug, CheckCircle2, Download, Plus, RefreshCcw, Search, ServerCog, ShieldAlert, X } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import type { DevOutletContext } from '../../components/DevAdminLayout'
import { dateTime, downloadCsv, jsonText } from './devUtils'

type Health={errors_1h:number;errors_24h:number;warnings_24h:number;open_incidents:number;appointments_24h:number;new_users_24h:number;new_businesses_24h:number}
type Incident={id:string;title:string;description:string|null;severity:'minor'|'major'|'critical';status:'investigating'|'identified'|'monitoring'|'resolved';started_at:string;resolved_at:string|null;created_at:string;updated_at:string}
type ErrorRow={id:string;level:'info'|'warning'|'error'|'fatal';source:string;message:string;stack?:string|null;metadata?:Record<string,unknown>;created_at:string;business_id:string|null;user_id:string|null}
type SchemaHealth={category:string;check_name:string;status:string;detail:string}

export function DevHealthPage(){
  const{role}=useOutletContext<DevOutletContext>();const[h,setH]=useState<Health|null>(null);const[inc,setInc]=useState<Incident[]>([]);const[errors,setErrors]=useState<ErrorRow[]>([]);const[checks,setChecks]=useState<SchemaHealth[]>([]);const[msg,setMsg]=useState('');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[severity,setSeverity]=useState<Incident['severity']>('minor');const[level,setLevel]=useState('all');const[source,setSource]=useState('all');const[q,setQ]=useState('');const[selectedError,setSelectedError]=useState<ErrorRow|null>(null);const[loading,setLoading]=useState(false)
  const canManage=['super_admin','ops'].includes(role)
  const load=useCallback(async()=>{setLoading(true);const[{data:hd,error:he},{data:i,error:ie},{data:e,error:ee},{data:c,error:ce}]=await Promise.all([supabase.rpc('dev_health_summary'),supabase.from('system_incidents').select('*').order('started_at',{ascending:false}).limit(100),supabase.from('app_error_logs').select('*').order('created_at',{ascending:false}).limit(500),supabase.rpc('app_schema_health')]);setH((hd||null) as Health|null);setInc((i||[]) as Incident[]);setErrors((e||[]) as ErrorRow[]);setChecks((c||[]) as SchemaHealth[]);const error=he||ie||ee; if(error)setMsg(error.message);else if(ce)setMsg(`Diagnóstico do schema indisponível: ${ce.message}`);setLoading(false)},[])
  useEffect(()=>{void load();const ch=supabase.channel('dev-health-enterprise').on('postgres_changes',{event:'*',schema:'public',table:'system_incidents'},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'app_error_logs'},load).subscribe();return()=>{void supabase.removeChannel(ch)}},[load])
  const filteredErrors=useMemo(()=>errors.filter(e=>(level==='all'||e.level===level)&&(source==='all'||e.source===source)&&(!q.trim()||`${e.message} ${e.source} ${e.business_id||''} ${e.user_id||''}`.toLowerCase().includes(q.toLowerCase()))),[errors,level,source,q])
  const sources=useMemo(()=>Array.from(new Set(errors.map(e=>e.source))).sort(),[errors])
  const schemaMissing=checks.filter(x=>x.status!=='OK').length
  async function create(e:FormEvent){e.preventDefault();if(!canManage||!title.trim())return;const{data:u}=await supabase.auth.getUser();const{error}=await supabase.from('system_incidents').insert({title:title.trim(),description:description.trim()||null,severity,status:'investigating',created_by:u.user?.id||null});setMsg(error?error.message:'Incidente criado.');if(!error){setTitle('');setDescription('');setSeverity('minor')}void load()}
  async function updateIncident(i:Incident,status:Incident['status']){if(!canManage)return;const payload:Record<string,unknown>={status};if(status==='resolved')payload.resolved_at=new Date().toISOString();else if(i.resolved_at)payload.resolved_at=null;const{error}=await supabase.from('system_incidents').update(payload).eq('id',i.id);setMsg(error?error.message:'Incidente atualizado.');void load()}
  function exportErrors(){downloadCsv(`erros-${new Date().toISOString().slice(0,10)}.csv`,filteredErrors.map(e=>({nivel:e.level,origem:e.source,mensagem:e.message,empresa:e.business_id,usuario:e.user_id,criado_em:e.created_at,stack:e.stack,metadata:e.metadata})))}
  return <>
    <header className="dev-page-head"><div><span className="eyebrow">OBSERVABILIDADE & CONFIABILIDADE</span><h1>Saúde do sistema</h1><p>Erros, incidentes, diagnóstico estrutural e indicadores operacionais da plataforma.</p></div><div className="dev-head-actions"><button className="button" onClick={exportErrors}><Download size={16}/>Exportar logs</button><button className="button" onClick={()=>void load()} disabled={loading}><RefreshCcw size={16}/>{loading?'Verificando...':'Atualizar'}</button></div></header>{msg&&<div className="notice">{msg}</div>}
    <div className="dev-kpis dev-kpis-health"><article className={(h?.errors_1h||0)>0?'danger':''}><Bug/><small>Erros 1h</small><strong>{h?.errors_1h||0}</strong><span>error + fatal</span></article><article className={(h?.errors_24h||0)>0?'danger':''}><AlertTriangle/><small>Erros 24h</small><strong>{h?.errors_24h||0}</strong><span>{h?.warnings_24h||0} warnings</span></article><article className={(h?.open_incidents||0)>0?'danger':''}><ShieldAlert/><small>Incidentes</small><strong>{h?.open_incidents||0}</strong><span>não resolvidos</span></article><article><Activity/><small>Agendamentos 24h</small><strong>{h?.appointments_24h||0}</strong><span>atividade operacional</span></article><article><Plus/><small>Novos usuários</small><strong>{h?.new_users_24h||0}</strong><span>últimas 24h</span></article><article className={schemaMissing?'danger':''}><ServerCog/><small>Schema</small><strong>{schemaMissing||0}</strong><span>{schemaMissing?'pendências':'estrutura OK'}</span></article></div>
    <div className="dev-split"><section className="dev-panel"><div className="dev-panel-head"><div><h2>Incidentes</h2><p>Registro operacional e acompanhamento do ciclo de resolução.</p></div></div>{canManage&&<form className="dev-incident-form" onSubmit={create}><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título do incidente" required/><select value={severity} onChange={e=>setSeverity(e.target.value as Incident['severity'])}><option value="minor">Minor</option><option value="major">Major</option><option value="critical">Critical</option></select><textarea className="input" rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição, impacto e contexto"/><button className="button button-primary"><Plus size={15}/>Criar incidente</button></form>}{inc.map(i=><article className={`dev-incident-card severity-${i.severity}`} key={i.id}><div><span className={`dev-priority ${i.severity==='critical'?'urgent':i.severity==='major'?'high':'normal'}`}>{i.severity}</span><h3>{i.title}</h3><small>{dateTime(i.started_at)} • {i.status}</small>{i.description&&<p>{i.description}</p>}</div>{canManage&&<select value={i.status} onChange={e=>void updateIncident(i,e.target.value as Incident['status'])}><option value="investigating">Investigando</option><option value="identified">Identificado</option><option value="monitoring">Monitorando</option><option value="resolved">Resolvido</option></select>}</article>)}{!inc.length&&<div className="dev-empty"><CheckCircle2/><p>Nenhum incidente registrado.</p></div>}</section>
    <section className="dev-panel"><div className="dev-panel-head"><div><h2>Diagnóstico do banco</h2><p>Tabelas, colunas e RPCs essenciais da versão Enterprise.</p></div><span className={`dev-status ${schemaMissing?'suspended':'active'}`}>{schemaMissing?`${schemaMissing} pendência(s)`:'OK'}</span></div><div className="dev-schema-mini">{checks.slice(0,30).map(x=><div key={`${x.category}-${x.check_name}`}><span className={x.status==='OK'?'ok':'missing'}>{x.status==='OK'?'✓':'!'}</span><div><b>{x.check_name}</b><small>{x.category} • {x.detail}</small></div></div>)}{!checks.length&&<p>Execute <code>MASTER_PRODUCTION_UPGRADE.sql</code> se o diagnóstico não estiver disponível.</p>}</div></section></div>
    <section className="dev-panel"><div className="dev-panel-head"><div><h2>Logs de aplicação</h2><p>{filteredErrors.length} registro(s) no filtro atual.</p></div></div><div className="dev-toolbar dev-toolbar-advanced"><div className="search-box"><Search size={17}/><input placeholder="Buscar mensagem, origem, empresa ou usuário" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Todos os níveis</option>{['fatal','error','warning','info'].map(x=><option key={x}>{x}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option value="all">Todas as origens</option>{sources.map(x=><option key={x}>{x}</option>)}</select></div><div className="dev-table-wrap"><table className="dev-table wide"><thead><tr><th>Data</th><th>Nível</th><th>Origem</th><th>Mensagem</th><th>Empresa</th><th>Usuário</th><th></th></tr></thead><tbody>{filteredErrors.map(e=><tr key={e.id}><td>{dateTime(e.created_at)}</td><td><span className={`dev-priority ${e.level==='fatal'?'urgent':e.level==='error'?'high':e.level==='warning'?'normal':'low'}`}>{e.level}</span></td><td>{e.source}</td><td className="dev-message-cell">{e.message}</td><td><code>{e.business_id?.slice(0,10)||'—'}</code></td><td><code>{e.user_id?.slice(0,10)||'—'}</code></td><td><button className="dev-table-action" onClick={()=>setSelectedError(e)}>Detalhes</button></td></tr>)}{!filteredErrors.length&&<tr><td colSpan={7}>Nenhum log encontrado.</td></tr>}</tbody></table></div></section>
    {selectedError&&<div className="dev-detail-backdrop" onClick={()=>setSelectedError(null)}><aside className="dev-detail-drawer dev-detail-wide" onClick={e=>e.stopPropagation()}><div className="dev-detail-head"><div><span className="eyebrow">LOG</span><h2>{selectedError.level.toUpperCase()}</h2><p>{selectedError.source} • {dateTime(selectedError.created_at)}</p></div><button onClick={()=>setSelectedError(null)}><X/></button></div><section className="dev-detail-section"><h3>Mensagem</h3><p className="dev-long-text">{selectedError.message}</p></section>{selectedError.stack&&<section className="dev-detail-section"><h3>Stack</h3><pre className="dev-code-block">{selectedError.stack}</pre></section>}<section className="dev-detail-section"><h3>Metadata</h3><pre className="dev-code-block">{jsonText(selectedError.metadata)}</pre></section><section className="dev-detail-section"><dl><div><dt>Empresa</dt><dd><code>{selectedError.business_id||'—'}</code></dd></div><div><dt>Usuário</dt><dd><code>{selectedError.user_id||'—'}</code></dd></div></dl></section></aside></div>}
  </>
}
