import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Copy, CreditCard, Edit3, Plus, RefreshCcw, Trash2, UsersRound } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import type { DevOutletContext } from '../../components/DevAdminLayout'
import { money } from './devUtils'

type Plan={id:string;code:string;name:string;description:string|null;price_monthly:number;max_professionals:number|null;max_team_members:number|null;features:Record<string,unknown>;active:boolean;sort_order:number;created_at?:string;updated_at?:string}
type Subscription={business_id:string;plan_id:string|null;status:string}
type FormState={id:string;code:string;name:string;description:string;price_monthly:number;max_professionals:string;max_team_members:string;active:boolean;sort_order:number;featuresText:string}
const blank:FormState={id:'',code:'',name:'',description:'',price_monthly:0,max_professionals:'',max_team_members:'',active:true,sort_order:0,featuresText:''}
const featureLines=(features:Record<string,unknown>)=>Array.isArray(features?.items)?(features.items as unknown[]).map(String).join('\n'):Object.entries(features||{}).filter(([,v])=>Boolean(v)).map(([k])=>k).join('\n')

export function DevPlansPage(){
  const{role}=useOutletContext<DevOutletContext>();const[rows,setRows]=useState<Plan[]>([]);const[subs,setSubs]=useState<Subscription[]>([]);const[form,setForm]=useState<FormState>({...blank});const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false)
  const canManage=['super_admin','billing'].includes(role)
  async function load(){setLoading(true);const[{data,error},{data:s,error:se}]=await Promise.all([supabase.from('subscription_plans').select('*').order('sort_order').order('name'),supabase.from('business_subscriptions').select('business_id,plan_id,status')]);setRows((data||[]) as Plan[]);setSubs((s||[]) as Subscription[]);if(error||se)setMsg(error?.message||se?.message||'Erro ao carregar planos.');setLoading(false)}useEffect(()=>{void load()},[])
  const metrics=useMemo(()=>rows.map(p=>{const linked=subs.filter(s=>s.plan_id===p.id);const paying=linked.filter(s=>['active','trialing'].includes(s.status));return{...p,total:linked.length,paying:paying.length,pastDue:linked.filter(s=>s.status==='past_due').length,mrr:paying.length*Number(p.price_monthly||0)}}),[rows,subs])
  const totals=useMemo(()=>({plans:rows.length,active:rows.filter(p=>p.active).length,subscriptions:subs.filter(s=>['active','trialing'].includes(s.status)).length,mrr:metrics.reduce((s,p)=>s+p.mrr,0)}),[rows,subs,metrics])
  function edit(p:Plan){setForm({id:p.id,code:p.code,name:p.name,description:p.description||'',price_monthly:Number(p.price_monthly),max_professionals:p.max_professionals==null?'':String(p.max_professionals),max_team_members:p.max_team_members==null?'':String(p.max_team_members),active:p.active,sort_order:p.sort_order,featuresText:featureLines(p.features)})}
  function clone(p:Plan){setForm({id:'',code:`${p.code}-copia`,name:`${p.name} — Cópia`,description:p.description||'',price_monthly:Number(p.price_monthly),max_professionals:p.max_professionals==null?'':String(p.max_professionals),max_team_members:p.max_team_members==null?'':String(p.max_team_members),active:false,sort_order:p.sort_order+1,featuresText:featureLines(p.features)})}
  async function save(e:FormEvent){e.preventDefault();if(!canManage)return;const items=form.featuresText.split('\n').map(x=>x.trim()).filter(Boolean);const payload={code:form.code.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-'),name:form.name.trim(),description:form.description.trim()||null,price_monthly:Number(form.price_monthly),max_professionals:form.max_professionals===''?null:Number(form.max_professionals),max_team_members:form.max_team_members===''?null:Number(form.max_team_members),active:form.active,sort_order:Number(form.sort_order),features:{items}};const query=form.id?supabase.from('subscription_plans').update(payload).eq('id',form.id):supabase.from('subscription_plans').insert(payload);const{error}=await query;setMsg(error?error.message:'Plano salvo com sucesso.');if(!error)setForm({...blank});void load()}
  async function remove(p:Plan){if(!canManage)return;const inUse=subs.filter(s=>s.plan_id===p.id).length;if(inUse>0){if(!window.confirm(`${p.name} possui ${inUse} empresa(s) vinculada(s). Desativar o plano em vez de excluir?`))return;const{error}=await supabase.from('subscription_plans').update({active:false}).eq('id',p.id);setMsg(error?error.message:'Plano desativado para preservar assinaturas.');void load();return}if(!window.confirm(`Excluir definitivamente o plano ${p.name}?`))return;const{error}=await supabase.from('subscription_plans').delete().eq('id',p.id);setMsg(error?error.message:'Plano excluído.');void load()}
  return <>
    <header className="dev-page-head"><div><span className="eyebrow">BILLING & CATÁLOGO INTERNO</span><h1>Planos</h1><p>Catálogo administrativo, limites, recursos e visão de assinaturas. Os preços não são exibidos na landing.</p></div><button className="button" onClick={()=>void load()} disabled={loading}><RefreshCcw size={16}/>{loading?'Atualizando...':'Atualizar'}</button></header>{msg&&<div className="notice">{msg}</div>}
    <div className="dev-kpis compact"><article><CreditCard/><small>Planos</small><strong>{totals.plans}</strong><span>{totals.active} ativos</span></article><article><UsersRound/><small>Assinaturas</small><strong>{totals.subscriptions}</strong><span>ativas + trial</span></article><article><CreditCard/><small>MRR estimado</small><strong>{money(totals.mrr)}</strong><span>baseado no preço mensal</span></article><article><CheckCircle2/><small>Empresas vinculadas</small><strong>{subs.length}</strong><span>todos os status</span></article></div>
    <div className="dev-split dev-split-plans"><section className="dev-panel"><div className="dev-panel-head"><div><h2>Catálogo</h2><p>{rows.length} plano(s) configurado(s).</p></div></div><div className="dev-plan-grid">{metrics.map(p=><article className={`dev-plan-card ${p.active?'':'inactive'}`} key={p.id}><div className="dev-plan-top"><div><span className={`dev-status ${p.active?'active':'archived'}`}>{p.active?'ativo':'inativo'}</span><h3>{p.name}</h3><small>{p.code}</small></div><strong>{money(p.price_monthly)}<small>/mês</small></strong></div><p>{p.description||'Sem descrição.'}</p><div className="dev-plan-metrics"><div><small>Assinantes</small><b>{p.paying}</b></div><div><small>MRR</small><b>{money(p.mrr)}</b></div><div><small>Past due</small><b>{p.pastDue}</b></div></div><div className="dev-feature-chips">{featureLines(p.features).split('\n').filter(Boolean).slice(0,6).map(x=><span key={x}>{x}</span>)}{!featureLines(p.features)&&<span>Sem recursos descritos</span>}</div><small className="dev-plan-limits">Profissionais: {p.max_professionals??'ilimitado'} • Equipe: {p.max_team_members??'ilimitado'}</small>{canManage&&<div className="dev-actions"><button onClick={()=>edit(p)}><Edit3 size={15}/>Editar</button><button onClick={()=>clone(p)}><Copy size={15}/>Duplicar</button><button className="danger" onClick={()=>void remove(p)}><Trash2 size={15}/>{p.total?'Desativar':'Excluir'}</button></div>}</article>)}{!rows.length&&<div className="dev-empty"><CreditCard/><p>Nenhum plano criado. O sistema não adiciona preços fictícios.</p></div>}</div></section>
    {canManage&&<form className="dev-panel dev-form dev-plan-form" onSubmit={save}><div className="dev-panel-head"><div><h2>{form.id?'Editar plano':'Novo plano'}</h2><p>Configuração interna do catálogo.</p></div>{form.id&&<button type="button" className="dev-icon-danger" onClick={()=>setForm({...blank})}>×</button>}</div><label>Nome<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Código técnico<input className="input" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="pro" required/></label><label>Descrição<textarea className="input" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-grid"><label>Preço mensal<input className="input" type="number" min="0" step="0.01" value={form.price_monthly} onChange={e=>setForm({...form,price_monthly:Number(e.target.value)})}/></label><label>Ordem<input className="input" type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label></div><div className="form-grid"><label>Máx. profissionais<input className="input" type="number" min="1" placeholder="Ilimitado" value={form.max_professionals} onChange={e=>setForm({...form,max_professionals:e.target.value})}/></label><label>Máx. equipe<input className="input" type="number" min="1" placeholder="Ilimitado" value={form.max_team_members} onChange={e=>setForm({...form,max_team_members:e.target.value})}/></label></div><label>Recursos <small>um por linha</small><textarea className="input" rows={7} value={form.featuresText} onChange={e=>setForm({...form,featuresText:e.target.value})} placeholder={'Agenda online\nCRM de clientes\nRelatórios avançados'}/></label><label className="check-line"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Plano disponível para novas atribuições</label><button className="button button-primary"><Plus size={16}/>{form.id?'Salvar alterações':'Criar plano'}</button></form>}</div>
  </>
}
