import { useCallback, useEffect, useMemo, useState } from 'react'
import { Clock3, Download, Headphones, MessageSquareText, RefreshCcw, Search, ShieldAlert, UserRoundCheck, X } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import type { DevOutletContext } from '../../components/DevAdminLayout'
import { dateTime, downloadCsv, hoursSince } from './devUtils'

type Ticket={id:string;business_id:string|null;created_by:string|null;subject:string;message:string;category:string;priority:'low'|'normal'|'high'|'urgent';status:string;assigned_to:string|null;internal_note:string|null;created_at:string;updated_at:string;businesses?:{name:string}|null}
type Admin={user_id:string;email:string|null;role:string;active:boolean}
const slaHours=(p:Ticket['priority'])=>p==='urgent'?2:p==='high'?8:p==='normal'?24:48

export function DevSupportPage(){
  const{role}=useOutletContext<DevOutletContext>();const[rows,setRows]=useState<Ticket[]>([]);const[admins,setAdmins]=useState<Admin[]>([]);const[status,setStatus]=useState('open');const[priority,setPriority]=useState('all');const[category,setCategory]=useState('all');const[q,setQ]=useState('');const[msg,setMsg]=useState('');const[selected,setSelected]=useState<Ticket|null>(null);const[loading,setLoading]=useState(false)
  const canManage=['super_admin','support'].includes(role)
  const load=useCallback(async()=>{setLoading(true);const[{data,error},{data:a,error:ae}]=await Promise.all([supabase.from('support_tickets').select('*,businesses(name)').order('created_at',{ascending:false}).limit(500),supabase.from('developer_admins').select('user_id,email,role,active').eq('active',true).order('email')]);setRows((data||[]) as Ticket[]);setAdmins((a||[]) as Admin[]);if(error||ae)setMsg(error?.message||ae?.message||'Erro ao carregar suporte.');setLoading(false)},[])
  useEffect(()=>{void load();const ch=supabase.channel('dev-support-enterprise').on('postgres_changes',{event:'*',schema:'public',table:'support_tickets'},load).subscribe();return()=>{void supabase.removeChannel(ch)}},[load])
  const filtered=useMemo(()=>rows.filter(t=>{const text=`${t.subject} ${t.message} ${t.businesses?.name||''}`.toLowerCase();return(status==='all'||t.status===status)&&(priority==='all'||t.priority===priority)&&(category==='all'||t.category===category)&&(!q.trim()||text.includes(q.toLowerCase()))}),[rows,status,priority,category,q])
  const categories=useMemo(()=>Array.from(new Set(rows.map(t=>t.category))).sort(),[rows])
  const stats=useMemo(()=>({open:rows.filter(t=>['open','in_progress','waiting_customer'].includes(t.status)).length,urgent:rows.filter(t=>t.priority==='urgent'&&!['resolved','closed'].includes(t.status)).length,overdue:rows.filter(t=>!['resolved','closed'].includes(t.status)&&hoursSince(t.created_at)>slaHours(t.priority)).length,resolvedToday:rows.filter(t=>['resolved','closed'].includes(t.status)&&new Date(t.updated_at).toDateString()===new Date().toDateString()).length}),[rows])
  async function patch(id:string,values:Record<string,unknown>){if(!canManage)return;const{error}=await supabase.from('support_tickets').update(values).eq('id',id);setMsg(error?error.message:'Ticket atualizado.');if(!error&&selected?.id===id)setSelected({...selected,...values} as Ticket);void load()}
  async function assignToMe(t:Ticket){if(!canManage)return;const{data}=await supabase.auth.getUser();if(!data.user)return;await patch(t.id,{assigned_to:data.user.id,status:t.status==='open'?'in_progress':t.status})}
  function exportRows(){downloadCsv(`suporte-${new Date().toISOString().slice(0,10)}.csv`,filtered.map(t=>({id:t.id,empresa:t.businesses?.name,assunto:t.subject,categoria:t.category,prioridade:t.priority,status:t.status,responsavel:admins.find(a=>a.user_id===t.assigned_to)?.email,criado_em:t.created_at,atualizado_em:t.updated_at,mensagem:t.message,nota_interna:t.internal_note})))}
  const assignee=(id:string|null)=>admins.find(a=>a.user_id===id)?.email||'Não atribuído'
  return <>
    <header className="dev-page-head"><div><span className="eyebrow">CENTRAL DE SUPORTE</span><h1>Suporte</h1><p>Fila operacional com prioridade, SLA, atribuição, histórico e acompanhamento em tempo real.</p></div><div className="dev-head-actions"><button className="button" onClick={exportRows}><Download size={16}/>Exportar</button><button className="button" onClick={()=>void load()} disabled={loading}><RefreshCcw size={16}/>{loading?'Atualizando...':'Atualizar'}</button></div></header>{msg&&<div className="notice">{msg}</div>}
    <div className="dev-kpis compact"><article><Headphones/><small>Fila aberta</small><strong>{stats.open}</strong><span>tickets em atendimento</span></article><article className={stats.urgent?'danger':''}><ShieldAlert/><small>Urgentes</small><strong>{stats.urgent}</strong><span>prioridade máxima</span></article><article className={stats.overdue?'danger':''}><Clock3/><small>SLA vencido</small><strong>{stats.overdue}</strong><span>tempo acima da meta</span></article><article><UserRoundCheck/><small>Resolvidos hoje</small><strong>{stats.resolvedToday}</strong><span>fechados no dia</span></article></div>
    <div className="dev-toolbar dev-toolbar-advanced"><div className="search-box"><Search size={17}/><input placeholder="Buscar assunto, mensagem ou empresa" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option>{['open','in_progress','waiting_customer','resolved','closed'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Todas as prioridades</option>{['urgent','high','normal','low'].map(x=><option key={x}>{x}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas as categorias</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div>
    <section className="dev-ticket-grid dev-ticket-grid-advanced">{filtered.map(t=>{const overdue=!['resolved','closed'].includes(t.status)&&hoursSince(t.created_at)>slaHours(t.priority);return <article className={`dev-ticket ${overdue?'dev-ticket-overdue':''}`} key={t.id}><div className="dev-ticket-head"><span className={`dev-priority ${t.priority}`}>{t.priority}</span><span className={`dev-status ${['resolved','closed'].includes(t.status)?'archived':'active'}`}>{t.status.replace('_',' ')}</span></div><h3>{t.subject}</h3><small>{t.businesses?.name||'Empresa indisponível'} • {dateTime(t.created_at)}</small><p>{t.message}</p><div className="dev-ticket-meta"><span><Clock3 size={13}/>{overdue?'SLA vencido':`${Math.max(0,Math.ceil(slaHours(t.priority)-hoursSince(t.created_at)))}h restantes`}</span><span><UserRoundCheck size={13}/>{assignee(t.assigned_to)}</span></div><div className="dev-actions"><button onClick={()=>setSelected(t)}>Detalhes</button>{canManage&&!t.assigned_to&&<button onClick={()=>void assignToMe(t)}>Assumir</button>}{canManage&&t.status!=='resolved'&&<button onClick={()=>void patch(t.id,{status:'resolved'})}>Resolver</button>}</div></article>})}{!filtered.length&&<div className="dev-empty"><Headphones/><p>Nenhum ticket neste filtro.</p></div>}</section>
    {selected&&<div className="dev-detail-backdrop" onClick={()=>setSelected(null)}><aside className="dev-detail-drawer dev-detail-wide" onClick={e=>e.stopPropagation()}><div className="dev-detail-head"><div><span className="eyebrow">TICKET</span><h2>{selected.subject}</h2><p>{selected.businesses?.name||'Empresa indisponível'}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="dev-detail-grid"><div><small>Status</small><strong>{selected.status}</strong></div><div><small>Prioridade</small><strong>{selected.priority}</strong></div><div><small>Categoria</small><strong>{selected.category}</strong></div><div><small>SLA</small><strong>{hoursSince(selected.created_at)>slaHours(selected.priority)?'Vencido':'Dentro da meta'}</strong></div></div><section className="dev-detail-section"><h3>Solicitação</h3><p className="dev-long-text">{selected.message}</p></section>{canManage&&<section className="dev-detail-section"><h3>Tratamento</h3><div className="form-grid"><label>Status<select value={selected.status} onChange={e=>void patch(selected.id,{status:e.target.value})}>{['open','in_progress','waiting_customer','resolved','closed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Prioridade<select value={selected.priority} onChange={e=>void patch(selected.id,{priority:e.target.value})}>{['low','normal','high','urgent'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Responsável<select className="input" value={selected.assigned_to||''} onChange={e=>void patch(selected.id,{assigned_to:e.target.value||null})}><option value="">Não atribuído</option>{admins.map(a=><option key={a.user_id} value={a.user_id}>{a.email||a.user_id} • {a.role}</option>)}</select></label><label>Nota interna<textarea className="input" rows={5} value={selected.internal_note||''} onChange={e=>setSelected({...selected,internal_note:e.target.value})}/></label><button className="button button-primary" onClick={()=>void patch(selected.id,{internal_note:selected.internal_note})}><MessageSquareText size={15}/>Salvar nota interna</button></section>}<section className="dev-detail-section"><h3>Metadados</h3><dl><div><dt>ID</dt><dd><code>{selected.id}</code></dd></div><div><dt>Criado em</dt><dd>{dateTime(selected.created_at)}</dd></div><div><dt>Atualizado em</dt><dd>{dateTime(selected.updated_at)}</dd></div><div><dt>Responsável</dt><dd>{assignee(selected.assigned_to)}</dd></div></dl></section></aside></div>}
  </>
}
