import { FormEvent, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Database, LockKeyhole, RefreshCcw, Save, ServerCog, ShieldCheck, UserPlus, UserX, UsersRound } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import type { DevOutletContext, DevRole } from '../../components/DevAdminLayout'
import { dateTime } from './devUtils'

type Settings={app_name:string;current_version:string;maintenance_mode:boolean;allow_new_signups:boolean;support_email:string|null;announcement:string|null;updated_at?:string;updated_by?:string|null}
type Admin={user_id:string;email:string|null;role:DevRole;active:boolean;created_at:string;updated_at?:string}
type SchemaHealth={category:string;check_name:string;status:string;detail:string}
const roleLabels:Record<DevRole,string>={super_admin:'Super Admin',support:'Suporte',billing:'Financeiro/Billing',ops:'Operações',read_only:'Somente leitura'}
const permissionRows=[
  ['Leitura global',true,true,true,true,true],['Empresas / suspensão',true,false,false,true,false],['Usuários / acesso',true,true,false,false,false],['Planos / billing',true,false,true,false,false],['Suporte',true,true,false,false,false],['Saúde / incidentes',true,false,false,true,false],['Configurações globais',true,false,false,true,false],['Administradores Dev',true,false,false,false,false]
]

export function DevSettingsPage(){
  const{role}=useOutletContext<DevOutletContext>();const[s,setS]=useState<Settings>({app_name:'BarberAgenda',current_version:'4.0.0',maintenance_mode:false,allow_new_signups:true,support_email:null,announcement:null});const[admins,setAdmins]=useState<Admin[]>([]);const[checks,setChecks]=useState<SchemaHealth[]>([]);const[email,setEmail]=useState('');const[newRole,setNewRole]=useState<DevRole>('read_only');const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false)
  const isSuper=role==='super_admin';const canOps=['super_admin','ops'].includes(role)
  async function load(){setLoading(true);setMsg('');const[{data:st,error:se},{data:ad,error:ae},{data:ch,error:ce}]=await Promise.all([supabase.from('system_settings').select('*').eq('id',1).single(),supabase.from('developer_admins').select('*').order('created_at'),supabase.rpc('app_schema_health')]);if(st)setS(st as Settings);setAdmins((ad||[]) as Admin[]);setChecks((ch||[]) as SchemaHealth[]);const error=se||ae;if(error)setMsg(error.message);else if(ce)setMsg(`Diagnóstico técnico indisponível: ${ce.message}`);setLoading(false)}useEffect(()=>{void load()},[])
  const health=useMemo(()=>({ok:checks.filter(x=>x.status==='OK').length,missing:checks.filter(x=>x.status!=='OK').length}),[checks])
  async function save(e:FormEvent){e.preventDefault();if(!canOps)return;if(s.maintenance_mode&&!window.confirm('O modo manutenção bloqueia o uso normal da aplicação para clientes. Confirmar configuração?'))return;const{data:u}=await supabase.auth.getUser();const{error}=await supabase.from('system_settings').update({...s,updated_by:u.user?.id||null,updated_at:new Date().toISOString()}).eq('id',1);setMsg(error?error.message:'Configurações globais salvas.');void load()}
  async function add(e:FormEvent){e.preventDefault();if(!isSuper)return;const normalized=email.trim().toLowerCase();if(!normalized)return;const{error}=await supabase.rpc('dev_add_developer_admin',{p_email:normalized,p_role:newRole});setMsg(error?error.message:'Administrador Dev adicionado.');if(!error)setEmail('');void load()}
  async function remove(a:Admin){if(!isSuper||!a.active)return;if(!window.confirm(`Desativar acesso Dev de ${a.email||a.user_id}?`))return;const{error}=await supabase.rpc('dev_remove_developer_admin',{p_user_id:a.user_id});setMsg(error?error.message:'Acesso Dev desativado.');void load()}
  return <>
    <header className="dev-page-head"><div><span className="eyebrow">PLATFORM CONTROL</span><h1>Configurações</h1><p>Controles globais, segurança, administradores, manutenção e diagnóstico da plataforma.</p></div><button className="button" onClick={()=>void load()} disabled={loading}><RefreshCcw size={16}/>{loading?'Atualizando...':'Atualizar'}</button></header>{msg&&<div className="notice">{msg}</div>}
    <div className="dev-kpis compact"><article className={s.maintenance_mode?'danger':''}><ServerCog/><small>Operação</small><strong>{s.maintenance_mode?'Manutenção':'Online'}</strong><span>estado global</span></article><article><UsersRound/><small>Cadastros</small><strong>{s.allow_new_signups?'Abertos':'Fechados'}</strong><span>novas contas</span></article><article><ShieldCheck/><small>Admins Dev</small><strong>{admins.filter(a=>a.active).length}</strong><span>acessos ativos</span></article><article className={health.missing?'danger':''}><Database/><small>Schema</small><strong>{health.missing}</strong><span>{health.missing?'pendência(s)':'estrutura OK'}</span></article></div>
    <div className="dev-settings-grid"><form className="dev-panel dev-form" onSubmit={save}><div className="dev-panel-head"><div><h2>Configuração global</h2><p>Valores consumidos pelo frontend e pela operação.</p></div><ServerCog/></div><label>Nome da aplicação<input className="input" value={s.app_name} onChange={e=>setS({...s,app_name:e.target.value})} disabled={!canOps}/></label><div className="form-grid"><label>Versão<input className="input" value={s.current_version} onChange={e=>setS({...s,current_version:e.target.value})} disabled={!canOps}/></label><label>E-mail de suporte<input className="input" type="email" value={s.support_email||''} onChange={e=>setS({...s,support_email:e.target.value||null})} disabled={!canOps}/></label></div><label>Mensagem global<textarea className="input" rows={4} value={s.announcement||''} onChange={e=>setS({...s,announcement:e.target.value||null})} disabled={!canOps} placeholder="Aviso opcional exibido aos usuários"/></label><div className="dev-toggle-card"><div><b>Modo manutenção</b><small>Use apenas em intervenções que exijam bloquear o uso normal do sistema.</small></div><label className="dev-switch"><input type="checkbox" checked={s.maintenance_mode} onChange={e=>setS({...s,maintenance_mode:e.target.checked})} disabled={!canOps}/><span/></label></div><div className="dev-toggle-card"><div><b>Novos cadastros</b><small>Controla a criação de novas contas/empresas pela aplicação.</small></div><label className="dev-switch"><input type="checkbox" checked={s.allow_new_signups} onChange={e=>setS({...s,allow_new_signups:e.target.checked})} disabled={!canOps}/><span/></label></div>{canOps&&<button className="button button-primary"><Save size={16}/>Salvar configurações</button>}<small className="dev-form-foot">Última atualização: {dateTime(s.updated_at)} • por {s.updated_by?.slice(0,12)||'sistema'}</small></form>
      <section className="dev-panel"><div className="dev-panel-head"><div><h2>Administradores Dev</h2><p>Acesso separado dos usuários das empresas.</p></div><ShieldCheck/></div>{admins.map(a=><div className="dev-admin-row" key={a.user_id}><div className="dev-admin-avatar">{(a.email||'?').slice(0,1).toUpperCase()}</div><div><b>{a.email||a.user_id}</b><small>{roleLabels[a.role]} • {a.active?'ativo':'desativado'} • desde {dateTime(a.created_at)}</small></div><span className={`dev-status ${a.active?'active':'archived'}`}>{a.active?'ativo':'off'}</span>{isSuper&&a.active&&<button className="dev-icon-danger" onClick={()=>void remove(a)} title="Desativar acesso"><UserX size={16}/></button>}</div>)}{isSuper&&<form className="dev-add-admin" onSubmit={add}><input className="input" type="email" placeholder="usuario@email.com" value={email} onChange={e=>setEmail(e.target.value)} required/><select value={newRole} onChange={e=>setNewRole(e.target.value as DevRole)}>{(Object.keys(roleLabels) as DevRole[]).map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select><button className="button button-primary"><UserPlus size={15}/>Adicionar</button></form>}</section>
    </div>
    <div className="dev-split"><section className="dev-panel"><div className="dev-panel-head"><div><h2>Matriz de permissões</h2><p>Resumo operacional das funções do Dev Console.</p></div><LockKeyhole/></div><div className="dev-table-wrap"><table className="dev-table dev-permission-table"><thead><tr><th>Permissão</th><th>Super</th><th>Support</th><th>Billing</th><th>Ops</th><th>Read only</th></tr></thead><tbody>{permissionRows.map(r=><tr key={String(r[0])}><td><b>{r[0]}</b></td>{r.slice(1).map((v,i)=><td key={i}>{v?<CheckCircle2 className="dev-check" size={17}/>:<span className="dev-dash">—</span>}</td>)}</tr>)}</tbody></table></div></section>
      <section className="dev-panel"><div className="dev-panel-head"><div><h2>Segurança & diagnóstico</h2><p>Baseline recomendado da plataforma.</p></div>{health.missing?<AlertTriangle/>:<CheckCircle2/>}</div><div className="dev-security-list"><div><ShieldCheck/><span><b>RLS nas tabelas expostas</b><small>Isolamento de dados por empresa.</small></span></div><div><LockKeyhole/><span><b>Service role fora do React</b><small>Ações privilegiadas ficam em Edge Functions/RPCs.</small></span></div><div><Database/><span><b>Diagnóstico do schema</b><small>{health.ok} OK • {health.missing} pendência(s).</small></span></div><div><ShieldCheck/><span><b>Auditoria</b><small>Ações Dev e CRUD das empresas possuem trilha.</small></span></div></div>{health.missing>0&&<div className="notice danger-notice">Há componentes ausentes. Execute <code>supabase/MASTER_PRODUCTION_UPGRADE.sql</code> e atualize esta página.</div>}</section>
    </div>
  </>
}
