import { useEffect, useMemo, useState } from 'react'
import { Ban, Copy, Download, KeyRound, RefreshCcw, Search, ShieldCheck, UserCheck, UserRoundX, Users, X } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import type { DevOutletContext } from '../../components/DevAdminLayout'
import { copyText, dateTime, downloadCsv } from './devUtils'

type Row={user_id:string;email:string;created_at:string;last_sign_in_at:string|null;email_confirmed_at:string|null;banned_until:string|null;business_id:string|null;business_name:string|null;business_role:string|null;membership_active:boolean|null}
type AuthFilter='all'|'active'|'banned'|'unconfirmed'|'never_login'

export function DevUsersPage(){
  const{role}=useOutletContext<DevOutletContext>()
  const[rows,setRows]=useState<Row[]>([]);const[q,setQ]=useState('');const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false)
  const[authFilter,setAuthFilter]=useState<AuthFilter>('all');const[roleFilter,setRoleFilter]=useState('all');const[selected,setSelected]=useState<Row|null>(null)
  const canManage=['super_admin','support'].includes(role)
  async function load(){setLoading(true);setMsg('');const{data,error}=await supabase.rpc('dev_list_users',{p_search:q.trim()||null,p_limit:500,p_offset:0});setRows((data||[]) as Row[]);if(error)setMsg(error.message);setLoading(false)}useEffect(()=>{void load()},[])
  const isBanned=(u:Row)=>Boolean(u.banned_until&&new Date(u.banned_until)>new Date())
  const filtered=useMemo(()=>rows.filter(u=>{
    const okAuth=authFilter==='all'||(authFilter==='active'&&!isBanned(u)&&!!u.email_confirmed_at)||(authFilter==='banned'&&isBanned(u))||(authFilter==='unconfirmed'&&!u.email_confirmed_at)||(authFilter==='never_login'&&!u.last_sign_in_at)
    const okRole=roleFilter==='all'||(roleFilter==='none'?!u.business_role:u.business_role===roleFilter)
    return okAuth&&okRole
  }),[rows,authFilter,roleFilter])
  const stats=useMemo(()=>({total:rows.length,banned:rows.filter(isBanned).length,unconfirmed:rows.filter(u=>!u.email_confirmed_at).length,unlinked:rows.filter(u=>!u.business_id).length,never:rows.filter(u=>!u.last_sign_in_at).length}),[rows])
  async function authAction(user:Row,action:'ban'|'unban'|'send_password_reset'){
    if(!canManage)return;if(action==='ban'&&!window.confirm(`Bloquear o login de ${user.email}?`))return
    const{error}=await supabase.functions.invoke('dev-user-admin',{body:{action,user_id:user.user_id,redirect_to:`${window.location.origin}/login?reset=1`}})
    setMsg(error?`Edge Function: ${error.message}`:action==='send_password_reset'?'E-mail de recuperação solicitado.':'Usuário atualizado.');void load()
  }
  async function toggleMember(user:Row){if(!canManage||!user.business_id)return;const next=!user.membership_active;if(!window.confirm(`${next?'Reativar':'Desativar'} vínculo de ${user.email} com ${user.business_name}?`))return;const{error}=await supabase.from('business_members').update({active:next}).eq('business_id',user.business_id).eq('user_id',user.user_id);setMsg(error?error.message:'Vínculo atualizado.');void load()}
  function exportRows(){downloadCsv(`usuarios-${new Date().toISOString().slice(0,10)}.csv`,filtered.map(u=>({email:u.email,user_id:u.user_id,confirmado:!!u.email_confirmed_at,bloqueado:isBanned(u),empresa:u.business_name,funcao:u.business_role,vinculo_ativo:u.membership_active,ultimo_login:u.last_sign_in_at,criado_em:u.created_at})))}
  return <>
    <header className="dev-page-head"><div><span className="eyebrow">AUTH & IDENTIDADE</span><h1>Usuários</h1><p>Contas de autenticação, segurança, confirmação de e-mail e vínculos com empresas.</p></div><div className="dev-head-actions"><button className="button" onClick={exportRows}><Download size={16}/>Exportar</button><button className="button" onClick={()=>void load()} disabled={loading}><RefreshCcw size={16}/>{loading?'Atualizando...':'Atualizar'}</button></div></header>{msg&&<div className="notice">{msg}</div>}
    <div className="dev-kpis compact dev-kpis-five"><article><Users/><small>Usuários</small><strong>{stats.total}</strong><span>contas encontradas</span></article><article className={stats.banned?'danger':''}><Ban/><small>Bloqueados</small><strong>{stats.banned}</strong><span>login suspenso</span></article><article><ShieldCheck/><small>Não confirmados</small><strong>{stats.unconfirmed}</strong><span>e-mail pendente</span></article><article><UserRoundX/><small>Sem empresa</small><strong>{stats.unlinked}</strong><span>sem vínculo ativo</span></article><article><KeyRound/><small>Nunca entraram</small><strong>{stats.never}</strong><span>sem último login</span></article></div>
    <div className="dev-toolbar dev-toolbar-advanced"><div className="search-box"><Search size={17}/><input placeholder="Buscar e-mail ou empresa" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}}/></div><select value={authFilter} onChange={e=>setAuthFilter(e.target.value as AuthFilter)}><option value="all">Todos os estados</option><option value="active">Ativos e confirmados</option><option value="banned">Bloqueados</option><option value="unconfirmed">E-mail não confirmado</option><option value="never_login">Nunca entraram</option></select><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="all">Todas as funções</option><option value="owner">Owner</option><option value="manager">Manager</option><option value="receptionist">Receptionist</option><option value="professional">Professional</option><option value="none">Sem função</option></select><button className="button button-primary" onClick={()=>void load()}>Buscar</button></div>
    <section className="dev-panel"><div className="dev-panel-head"><div><h2>Diretório de usuários</h2><p>{filtered.length} resultado(s).</p></div></div><div className="dev-table-wrap"><table className="dev-table wide"><thead><tr><th>Usuário</th><th>Empresa</th><th>Função</th><th>E-mail</th><th>Auth</th><th>Último login</th><th>Criado</th><th>Ações</th></tr></thead><tbody>{filtered.map(u=>{const banned=isBanned(u);return <tr key={`${u.user_id}-${u.business_id||'none'}`}><td><b>{u.email}</b><small>{u.user_id.slice(0,12)}…</small></td><td>{u.business_name||'Sem empresa'}</td><td>{u.business_role||'—'} {u.business_id&&<span className={`dev-status ${u.membership_active?'active':'suspended'}`}>{u.membership_active?'vínculo ativo':'vínculo inativo'}</span>}</td><td><span className={`dev-status ${u.email_confirmed_at?'active':'suspended'}`}>{u.email_confirmed_at?'confirmado':'pendente'}</span></td><td><span className={`dev-status ${banned?'suspended':'active'}`}>{banned?'bloqueado':'liberado'}</span></td><td>{dateTime(u.last_sign_in_at)}</td><td>{dateTime(u.created_at)}</td><td><div className="dev-actions"><button onClick={()=>setSelected(u)}>Detalhes</button>{canManage&&<>{banned?<button onClick={()=>void authAction(u,'unban')}><UserCheck size={15}/>Liberar</button>:<button className="danger" onClick={()=>void authAction(u,'ban')}><Ban size={15}/>Bloquear</button>}<button onClick={()=>void authAction(u,'send_password_reset')}><KeyRound size={15}/>Reset</button>{u.business_id&&<button onClick={()=>void toggleMember(u)}>{u.membership_active?'Desativar vínculo':'Reativar vínculo'}</button>}</>}</div></td></tr>})}{!filtered.length&&<tr><td colSpan={8}>Nenhum usuário encontrado.</td></tr>}</tbody></table></div></section>
    {selected&&<div className="dev-detail-backdrop" onClick={()=>setSelected(null)}><aside className="dev-detail-drawer" onClick={e=>e.stopPropagation()}><div className="dev-detail-head"><div><span className="eyebrow">USUÁRIO</span><h2>{selected.email}</h2><p>{selected.business_name||'Sem empresa vinculada'}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="dev-detail-grid"><div><small>Auth</small><strong>{isBanned(selected)?'Bloqueado':'Liberado'}</strong></div><div><small>E-mail</small><strong>{selected.email_confirmed_at?'Confirmado':'Pendente'}</strong></div><div><small>Função</small><strong>{selected.business_role||'—'}</strong></div><div><small>Vínculo</small><strong>{selected.business_id?(selected.membership_active?'Ativo':'Inativo'):'Sem empresa'}</strong></div></div><section className="dev-detail-section"><h3>Dados técnicos</h3><dl><div><dt>User ID</dt><dd><code>{selected.user_id}</code></dd></div><div><dt>Business ID</dt><dd><code>{selected.business_id||'—'}</code></dd></div><div><dt>Último login</dt><dd>{dateTime(selected.last_sign_in_at)}</dd></div><div><dt>Confirmado em</dt><dd>{dateTime(selected.email_confirmed_at)}</dd></div><div><dt>Criado em</dt><dd>{dateTime(selected.created_at)}</dd></div><div><dt>Ban até</dt><dd>{dateTime(selected.banned_until)}</dd></div></dl></section><div className="dev-detail-actions"><button className="button" onClick={()=>void copyText(selected.user_id)}><Copy size={15}/>Copiar ID</button>{canManage&&<button className="button" onClick={()=>void authAction(selected,'send_password_reset')}><KeyRound size={15}/>Recuperar senha</button>}</div></aside></div>}
  </>
}
